/* 포커스 에어 공항 목록 (692곳) — code: IATA 코드, en: 영어 방송용 이름, lat/lon: 위도·경도(도) */
window.AIRPORTS = [
  // 한국
  { code: 'ICN', en: 'Incheon', city: '인천', country: '대한민국', region: '한국', lat: 37.46, lon: 126.44 },
  { code: 'GMP', en: 'Seoul Gimpo', city: '서울 김포', country: '대한민국', region: '한국', lat: 37.56, lon: 126.80 },
  { code: 'PUS', en: 'Busan', city: '부산 김해', country: '대한민국', region: '한국', lat: 35.18, lon: 128.94 },
  { code: 'CJU', en: 'Jeju', city: '제주', country: '대한민국', region: '한국', lat: 33.51, lon: 126.49 },
  { code: 'CJJ', en: 'Cheongju', city: '청주', country: '대한민국', region: '한국', lat: 36.72, lon: 127.50 },
  { code: 'TAE', en: 'Daegu', city: '대구', country: '대한민국', region: '한국', lat: 35.89, lon: 128.66 },
  { code: 'KWJ', en: 'Gwangju', city: '광주', country: '대한민국', region: '한국', lat: 35.13, lon: 126.81 },
  { code: 'RSU', en: 'Yeosu', city: '여수', country: '대한민국', region: '한국', lat: 34.84, lon: 127.62 },
  { code: 'USN', en: 'Ulsan', city: '울산', country: '대한민국', region: '한국', lat: 35.59, lon: 129.35 },
  { code: 'YNY', en: 'Yangyang', city: '양양', country: '대한민국', region: '한국', lat: 38.06, lon: 128.67 },
  // 일본
  { code: 'NRT', en: 'Tokyo Narita', city: '도쿄 나리타', country: '일본', region: '일본', lat: 35.77, lon: 140.39 },
  { code: 'HND', en: 'Tokyo Haneda', city: '도쿄 하네다', country: '일본', region: '일본', lat: 35.55, lon: 139.78 },
  { code: 'KIX', en: 'Osaka Kansai', city: '오사카 간사이', country: '일본', region: '일본', lat: 34.43, lon: 135.23 },
  { code: 'FUK', en: 'Fukuoka', city: '후쿠오카', country: '일본', region: '일본', lat: 33.59, lon: 130.45 },
  { code: 'CTS', en: 'Sapporo', city: '삿포로', country: '일본', region: '일본', lat: 42.78, lon: 141.69 },
  { code: 'OKA', en: 'Okinawa', city: '오키나와', country: '일본', region: '일본', lat: 26.20, lon: 127.65 },
  // 중화권
  { code: 'PEK', en: 'Beijing', city: '베이징', country: '중국', region: '중화권', lat: 40.08, lon: 116.58 },
  { code: 'PVG', en: 'Shanghai', city: '상하이', country: '중국', region: '중화권', lat: 31.14, lon: 121.81 },
  { code: 'HKG', en: 'Hong Kong', city: '홍콩', country: '홍콩', region: '중화권', lat: 22.31, lon: 113.91 },
  { code: 'TPE', en: 'Taipei', city: '타이베이', country: '대만', region: '중화권', lat: 25.08, lon: 121.23 },
  // 동남아시아
  { code: 'BKK', en: 'Bangkok', city: '방콕', country: '태국', region: '동남아시아', lat: 13.69, lon: 100.75 },
  { code: 'HAN', en: 'Hanoi', city: '하노이', country: '베트남', region: '동남아시아', lat: 21.22, lon: 105.81 },
  { code: 'DAD', en: 'Da Nang', city: '다낭', country: '베트남', region: '동남아시아', lat: 16.04, lon: 108.20 },
  { code: 'SGN', en: 'Ho Chi Minh City', city: '호찌민', country: '베트남', region: '동남아시아', lat: 10.82, lon: 106.66 },
  { code: 'MNL', en: 'Manila', city: '마닐라', country: '필리핀', region: '동남아시아', lat: 14.51, lon: 121.02 },
  { code: 'CEB', en: 'Cebu', city: '세부', country: '필리핀', region: '동남아시아', lat: 10.31, lon: 123.98 },
  { code: 'SIN', en: 'Singapore', city: '싱가포르', country: '싱가포르', region: '동남아시아', lat: 1.36, lon: 103.99 },
  { code: 'KUL', en: 'Kuala Lumpur', city: '쿠알라룸푸르', country: '말레이시아', region: '동남아시아', lat: 2.75, lon: 101.71 },
  { code: 'DPS', en: 'Bali', city: '발리', country: '인도네시아', region: '동남아시아', lat: -8.75, lon: 115.17 },
  // 아시아 기타·중동
  { code: 'UBN', en: 'Ulaanbaatar', city: '울란바토르', country: '몽골', region: '아시아·중동', lat: 47.65, lon: 106.82 },
  { code: 'VVO', en: 'Vladivostok', city: '블라디보스토크', country: '러시아', region: '아시아·중동', lat: 43.40, lon: 132.15 },
  { code: 'DEL', en: 'Delhi', city: '델리', country: '인도', region: '아시아·중동', lat: 28.56, lon: 77.10 },
  { code: 'DXB', en: 'Dubai', city: '두바이', country: '아랍에미리트', region: '아시아·중동', lat: 25.25, lon: 55.36 },
  { code: 'IST', en: 'Istanbul', city: '이스탄불', country: '튀르키예', region: '아시아·중동', lat: 41.26, lon: 28.74 },
  // 오세아니아·태평양
  { code: 'GUM', en: 'Guam', city: '괌', country: '미국령 괌', region: '오세아니아·태평양', lat: 13.48, lon: 144.80 },
  { code: 'HNL', en: 'Honolulu', city: '호놀룰루', country: '미국', region: '오세아니아·태평양', lat: 21.32, lon: -157.92 },
  { code: 'SYD', en: 'Sydney', city: '시드니', country: '호주', region: '오세아니아·태평양', lat: -33.95, lon: 151.18 },
  { code: 'AKL', en: 'Auckland', city: '오클랜드', country: '뉴질랜드', region: '오세아니아·태평양', lat: -37.01, lon: 174.79 },
  // 아메리카
  { code: 'YVR', en: 'Vancouver', city: '밴쿠버', country: '캐나다', region: '아메리카', lat: 49.19, lon: -123.18 },
  { code: 'SEA', en: 'Seattle', city: '시애틀', country: '미국', region: '아메리카', lat: 47.45, lon: -122.31 },
  { code: 'SFO', en: 'San Francisco', city: '샌프란시스코', country: '미국', region: '아메리카', lat: 37.62, lon: -122.38 },
  { code: 'LAX', en: 'Los Angeles', city: '로스앤젤레스', country: '미국', region: '아메리카', lat: 33.94, lon: -118.41 },
  { code: 'JFK', en: 'New York', city: '뉴욕', country: '미국', region: '아메리카', lat: 40.64, lon: -73.78 },
  { code: 'GRU', en: 'Sao Paulo', city: '상파울루', country: '브라질', region: '아메리카', lat: -23.43, lon: -46.47 },
  // 유럽·아프리카
  { code: 'LHR', en: 'London', city: '런던', country: '영국', region: '유럽·아프리카', lat: 51.47, lon: -0.45 },
  { code: 'CDG', en: 'Paris', city: '파리', country: '프랑스', region: '유럽·아프리카', lat: 49.01, lon: 2.55 },
  { code: 'AMS', en: 'Amsterdam', city: '암스테르담', country: '네덜란드', region: '유럽·아프리카', lat: 52.31, lon: 4.76 },
  { code: 'FRA', en: 'Frankfurt', city: '프랑크푸르트', country: '독일', region: '유럽·아프리카', lat: 50.03, lon: 8.56 },
  { code: 'ZRH', en: 'Zurich', city: '취리히', country: '스위스', region: '유럽·아프리카', lat: 47.46, lon: 8.55 },
  { code: 'PRG', en: 'Prague', city: '프라하', country: '체코', region: '유럽·아프리카', lat: 50.10, lon: 14.26 },
  { code: 'FCO', en: 'Rome', city: '로마', country: '이탈리아', region: '유럽·아프리카', lat: 41.80, lon: 12.25 },
  { code: 'BCN', en: 'Barcelona', city: '바르셀로나', country: '스페인', region: '유럽·아프리카', lat: 41.30, lon: 2.08 },
  { code: 'HEL', en: 'Helsinki', city: '헬싱키', country: '핀란드', region: '유럽·아프리카', lat: 60.32, lon: 24.96 },
  { code: 'CAI', en: 'Cairo', city: '카이로', country: '이집트', region: '유럽·아프리카', lat: 30.12, lon: 31.41 },
  { code: 'JNB', en: 'Johannesburg', city: '요하네스버그', country: '남아프리카공화국', region: '유럽·아프리카', lat: -26.14, lon: 28.24 },
  // ---- 추가 공항 ----
  // 한국
  { code: 'MWX', en: 'Muan', city: '무안', country: '대한민국', region: '한국', lat: 34.99, lon: 126.38 },
  { code: 'KPO', en: 'Pohang', city: '포항경주', country: '대한민국', region: '한국', lat: 35.99, lon: 129.42 },
  { code: 'HIN', en: 'Sacheon', city: '사천', country: '대한민국', region: '한국', lat: 35.09, lon: 128.07 },
  { code: 'WJU', en: 'Wonju', city: '원주', country: '대한민국', region: '한국', lat: 37.44, lon: 127.96 },
  { code: 'KUV', en: 'Gunsan', city: '군산', country: '대한민국', region: '한국', lat: 35.90, lon: 126.62 },
  // 일본
  { code: 'NGO', en: 'Nagoya', city: '나고야', country: '일본', region: '일본', lat: 34.86, lon: 136.81 },
  { code: 'ITM', en: 'Osaka Itami', city: '오사카 이타미', country: '일본', region: '일본', lat: 34.79, lon: 135.44 },
  { code: 'KOJ', en: 'Kagoshima', city: '가고시마', country: '일본', region: '일본', lat: 31.80, lon: 130.72 },
  { code: 'HIJ', en: 'Hiroshima', city: '히로시마', country: '일본', region: '일본', lat: 34.44, lon: 132.92 },
  { code: 'SDJ', en: 'Sendai', city: '센다이', country: '일본', region: '일본', lat: 38.14, lon: 140.92 },
  { code: 'KMJ', en: 'Kumamoto', city: '구마모토', country: '일본', region: '일본', lat: 32.84, lon: 130.86 },
  { code: 'OIT', en: 'Oita', city: '오이타', country: '일본', region: '일본', lat: 33.48, lon: 131.74 },
  { code: 'NGS', en: 'Nagasaki', city: '나가사키', country: '일본', region: '일본', lat: 32.92, lon: 129.91 },
  { code: 'MYJ', en: 'Matsuyama', city: '마쓰야마', country: '일본', region: '일본', lat: 33.83, lon: 132.70 },
  { code: 'TAK', en: 'Takamatsu', city: '다카마쓰', country: '일본', region: '일본', lat: 34.21, lon: 134.02 },
  { code: 'OKJ', en: 'Okayama', city: '오카야마', country: '일본', region: '일본', lat: 34.76, lon: 133.86 },
  { code: 'KIJ', en: 'Niigata', city: '니가타', country: '일본', region: '일본', lat: 37.96, lon: 139.12 },
  { code: 'AOJ', en: 'Aomori', city: '아오모리', country: '일본', region: '일본', lat: 40.73, lon: 140.69 },
  { code: 'HKD', en: 'Hakodate', city: '하코다테', country: '일본', region: '일본', lat: 41.77, lon: 140.82 },
  { code: 'KMQ', en: 'Komatsu', city: '고마쓰', country: '일본', region: '일본', lat: 36.39, lon: 136.41 },
  { code: 'FSZ', en: 'Shizuoka', city: '시즈오카', country: '일본', region: '일본', lat: 34.80, lon: 138.19 },
  { code: 'KKJ', en: 'Kitakyushu', city: '기타큐슈', country: '일본', region: '일본', lat: 33.85, lon: 131.03 },
  { code: 'ISG', en: 'Ishigaki', city: '이시가키', country: '일본', region: '일본', lat: 24.40, lon: 124.25 },
  { code: 'MMY', en: 'Miyako', city: '미야코', country: '일본', region: '일본', lat: 24.78, lon: 125.30 },
  // 중화권
  { code: 'PKX', en: 'Beijing Daxing', city: '베이징 다싱', country: '중국', region: '중화권', lat: 39.51, lon: 116.41 },
  { code: 'SHA', en: 'Shanghai Hongqiao', city: '상하이 훙차오', country: '중국', region: '중화권', lat: 31.20, lon: 121.34 },
  { code: 'CAN', en: 'Guangzhou', city: '광저우', country: '중국', region: '중화권', lat: 23.39, lon: 113.30 },
  { code: 'SZX', en: 'Shenzhen', city: '선전', country: '중국', region: '중화권', lat: 22.64, lon: 113.81 },
  { code: 'CTU', en: 'Chengdu Shuangliu', city: '청두 솽류', country: '중국', region: '중화권', lat: 30.56, lon: 103.95 },
  { code: 'TFU', en: 'Chengdu Tianfu', city: '청두 톈푸', country: '중국', region: '중화권', lat: 30.31, lon: 104.44 },
  { code: 'CKG', en: 'Chongqing', city: '충칭', country: '중국', region: '중화권', lat: 29.72, lon: 106.64 },
  { code: 'XIY', en: "Xi'an", city: '시안', country: '중국', region: '중화권', lat: 34.45, lon: 108.75 },
  { code: 'KMG', en: 'Kunming', city: '쿤밍', country: '중국', region: '중화권', lat: 25.10, lon: 102.93 },
  { code: 'HGH', en: 'Hangzhou', city: '항저우', country: '중국', region: '중화권', lat: 30.23, lon: 120.43 },
  { code: 'NKG', en: 'Nanjing', city: '난징', country: '중국', region: '중화권', lat: 31.74, lon: 118.86 },
  { code: 'TAO', en: 'Qingdao', city: '칭다오', country: '중국', region: '중화권', lat: 36.36, lon: 120.09 },
  { code: 'DLC', en: 'Dalian', city: '다롄', country: '중국', region: '중화권', lat: 38.97, lon: 121.54 },
  { code: 'SHE', en: 'Shenyang', city: '선양', country: '중국', region: '중화권', lat: 41.64, lon: 123.48 },
  { code: 'HRB', en: 'Harbin', city: '하얼빈', country: '중국', region: '중화권', lat: 45.62, lon: 126.25 },
  { code: 'YNJ', en: 'Yanji', city: '옌지', country: '중국', region: '중화권', lat: 42.88, lon: 129.45 },
  { code: 'TSN', en: 'Tianjin', city: '톈진', country: '중국', region: '중화권', lat: 39.12, lon: 117.35 },
  { code: 'CGO', en: 'Zhengzhou', city: '정저우', country: '중국', region: '중화권', lat: 34.52, lon: 113.84 },
  { code: 'WUH', en: 'Wuhan', city: '우한', country: '중국', region: '중화권', lat: 30.78, lon: 114.21 },
  { code: 'CSX', en: 'Changsha', city: '창사', country: '중국', region: '중화권', lat: 28.19, lon: 113.22 },
  { code: 'XMN', en: 'Xiamen', city: '샤먼', country: '중국', region: '중화권', lat: 24.54, lon: 118.13 },
  { code: 'SYX', en: 'Sanya', city: '싼야', country: '중국', region: '중화권', lat: 18.30, lon: 109.41 },
  { code: 'HAK', en: 'Haikou', city: '하이커우', country: '중국', region: '중화권', lat: 19.94, lon: 110.46 },
  { code: 'URC', en: 'Urumqi', city: '우루무치', country: '중국', region: '중화권', lat: 43.91, lon: 87.47 },
  { code: 'LXA', en: 'Lhasa', city: '라싸', country: '중국', region: '중화권', lat: 29.30, lon: 90.91 },
  { code: 'MFM', en: 'Macau', city: '마카오', country: '마카오', region: '중화권', lat: 22.15, lon: 113.59 },
  { code: 'TSA', en: 'Taipei Songshan', city: '타이베이 쑹산', country: '대만', region: '중화권', lat: 25.07, lon: 121.55 },
  { code: 'KHH', en: 'Kaohsiung', city: '가오슝', country: '대만', region: '중화권', lat: 22.58, lon: 120.35 },
  { code: 'RMQ', en: 'Taichung', city: '타이중', country: '대만', region: '중화권', lat: 24.26, lon: 120.62 },
  // 동남아시아
  { code: 'DMK', en: 'Bangkok Don Mueang', city: '방콕 돈므앙', country: '태국', region: '동남아시아', lat: 13.91, lon: 100.61 },
  { code: 'HKT', en: 'Phuket', city: '푸껫', country: '태국', region: '동남아시아', lat: 8.11, lon: 98.32 },
  { code: 'CNX', en: 'Chiang Mai', city: '치앙마이', country: '태국', region: '동남아시아', lat: 18.77, lon: 98.96 },
  { code: 'PQC', en: 'Phu Quoc', city: '푸꾸옥', country: '베트남', region: '동남아시아', lat: 10.17, lon: 103.99 },
  { code: 'CXR', en: 'Nha Trang', city: '나트랑', country: '베트남', region: '동남아시아', lat: 12.00, lon: 109.22 },
  { code: 'HPH', en: 'Hai Phong', city: '하이퐁', country: '베트남', region: '동남아시아', lat: 20.82, lon: 106.72 },
  { code: 'VTE', en: 'Vientiane', city: '비엔티안', country: '라오스', region: '동남아시아', lat: 17.99, lon: 102.56 },
  { code: 'PNH', en: 'Phnom Penh', city: '프놈펜', country: '캄보디아', region: '동남아시아', lat: 11.55, lon: 104.84 },
  { code: 'SAI', en: 'Siem Reap', city: '시엠레아프', country: '캄보디아', region: '동남아시아', lat: 13.37, lon: 104.22 },
  { code: 'RGN', en: 'Yangon', city: '양곤', country: '미얀마', region: '동남아시아', lat: 16.91, lon: 96.13 },
  { code: 'CRK', en: 'Clark', city: '클라크', country: '필리핀', region: '동남아시아', lat: 15.19, lon: 120.56 },
  { code: 'KLO', en: 'Kalibo', city: '칼리보(보라카이)', country: '필리핀', region: '동남아시아', lat: 11.68, lon: 122.38 },
  { code: 'BKI', en: 'Kota Kinabalu', city: '코타키나발루', country: '말레이시아', region: '동남아시아', lat: 5.94, lon: 116.05 },
  { code: 'PEN', en: 'Penang', city: '페낭', country: '말레이시아', region: '동남아시아', lat: 5.30, lon: 100.28 },
  { code: 'LGK', en: 'Langkawi', city: '랑카위', country: '말레이시아', region: '동남아시아', lat: 6.33, lon: 99.73 },
  { code: 'BWN', en: 'Bandar Seri Begawan', city: '반다르스리브가완', country: '브루나이', region: '동남아시아', lat: 4.94, lon: 114.93 },
  { code: 'CGK', en: 'Jakarta', city: '자카르타', country: '인도네시아', region: '동남아시아', lat: -6.13, lon: 106.66 },
  { code: 'SUB', en: 'Surabaya', city: '수라바야', country: '인도네시아', region: '동남아시아', lat: -7.38, lon: 112.79 },
  // 아시아 기타·중동
  { code: 'BOM', en: 'Mumbai', city: '뭄바이', country: '인도', region: '아시아·중동', lat: 19.09, lon: 72.87 },
  { code: 'BLR', en: 'Bengaluru', city: '벵갈루루', country: '인도', region: '아시아·중동', lat: 13.20, lon: 77.71 },
  { code: 'MAA', en: 'Chennai', city: '첸나이', country: '인도', region: '아시아·중동', lat: 12.99, lon: 80.17 },
  { code: 'CCU', en: 'Kolkata', city: '콜카타', country: '인도', region: '아시아·중동', lat: 22.65, lon: 88.45 },
  { code: 'KTM', en: 'Kathmandu', city: '카트만두', country: '네팔', region: '아시아·중동', lat: 27.70, lon: 85.36 },
  { code: 'DAC', en: 'Dhaka', city: '다카', country: '방글라데시', region: '아시아·중동', lat: 23.84, lon: 90.40 },
  { code: 'CMB', en: 'Colombo', city: '콜롬보', country: '스리랑카', region: '아시아·중동', lat: 7.18, lon: 79.88 },
  { code: 'MLE', en: 'Male', city: '말레', country: '몰디브', region: '아시아·중동', lat: 4.19, lon: 73.53 },
  { code: 'ISB', en: 'Islamabad', city: '이슬라마바드', country: '파키스탄', region: '아시아·중동', lat: 33.55, lon: 72.83 },
  { code: 'TAS', en: 'Tashkent', city: '타슈켄트', country: '우즈베키스탄', region: '아시아·중동', lat: 41.26, lon: 69.28 },
  { code: 'ALA', en: 'Almaty', city: '알마티', country: '카자흐스탄', region: '아시아·중동', lat: 43.35, lon: 77.04 },
  { code: 'NQZ', en: 'Astana', city: '아스타나', country: '카자흐스탄', region: '아시아·중동', lat: 51.02, lon: 71.47 },
  { code: 'KHV', en: 'Khabarovsk', city: '하바롭스크', country: '러시아', region: '아시아·중동', lat: 48.53, lon: 135.19 },
  { code: 'UUS', en: 'Yuzhno-Sakhalinsk', city: '유즈노사할린스크', country: '러시아', region: '아시아·중동', lat: 46.89, lon: 142.72 },
  { code: 'IKT', en: 'Irkutsk', city: '이르쿠츠크', country: '러시아', region: '아시아·중동', lat: 52.27, lon: 104.39 },
  { code: 'OVB', en: 'Novosibirsk', city: '노보시비르스크', country: '러시아', region: '아시아·중동', lat: 55.01, lon: 82.65 },
  { code: 'DOH', en: 'Doha', city: '도하', country: '카타르', region: '아시아·중동', lat: 25.27, lon: 51.61 },
  { code: 'AUH', en: 'Abu Dhabi', city: '아부다비', country: '아랍에미리트', region: '아시아·중동', lat: 24.43, lon: 54.65 },
  { code: 'RUH', en: 'Riyadh', city: '리야드', country: '사우디아라비아', region: '아시아·중동', lat: 24.96, lon: 46.70 },
  { code: 'JED', en: 'Jeddah', city: '제다', country: '사우디아라비아', region: '아시아·중동', lat: 21.68, lon: 39.16 },
  { code: 'MCT', en: 'Muscat', city: '무스카트', country: '오만', region: '아시아·중동', lat: 23.59, lon: 58.28 },
  { code: 'KWI', en: 'Kuwait', city: '쿠웨이트', country: '쿠웨이트', region: '아시아·중동', lat: 29.24, lon: 47.97 },
  { code: 'BAH', en: 'Bahrain', city: '바레인', country: '바레인', region: '아시아·중동', lat: 26.27, lon: 50.63 },
  { code: 'AMM', en: 'Amman', city: '암만', country: '요르단', region: '아시아·중동', lat: 31.72, lon: 35.99 },
  { code: 'TLV', en: 'Tel Aviv', city: '텔아비브', country: '이스라엘', region: '아시아·중동', lat: 32.01, lon: 34.89 },
  { code: 'SAW', en: 'Istanbul Sabiha Gokcen', city: '이스탄불 사비하괵첸', country: '튀르키예', region: '아시아·중동', lat: 40.90, lon: 29.31 },
  { code: 'AYT', en: 'Antalya', city: '안탈리아', country: '튀르키예', region: '아시아·중동', lat: 36.90, lon: 30.80 },
  // 오세아니아·태평양
  { code: 'MEL', en: 'Melbourne', city: '멜버른', country: '호주', region: '오세아니아·태평양', lat: -37.67, lon: 144.84 },
  { code: 'BNE', en: 'Brisbane', city: '브리즈번', country: '호주', region: '오세아니아·태평양', lat: -27.38, lon: 153.12 },
  { code: 'PER', en: 'Perth', city: '퍼스', country: '호주', region: '오세아니아·태평양', lat: -31.94, lon: 115.97 },
  { code: 'ADL', en: 'Adelaide', city: '애들레이드', country: '호주', region: '오세아니아·태평양', lat: -34.95, lon: 138.53 },
  { code: 'CNS', en: 'Cairns', city: '케언스', country: '호주', region: '오세아니아·태평양', lat: -16.88, lon: 145.75 },
  { code: 'OOL', en: 'Gold Coast', city: '골드코스트', country: '호주', region: '오세아니아·태평양', lat: -28.16, lon: 153.51 },
  { code: 'DRW', en: 'Darwin', city: '다윈', country: '호주', region: '오세아니아·태평양', lat: -12.41, lon: 130.88 },
  { code: 'CHC', en: 'Christchurch', city: '크라이스트처치', country: '뉴질랜드', region: '오세아니아·태평양', lat: -43.49, lon: 172.53 },
  { code: 'ZQN', en: 'Queenstown', city: '퀸스타운', country: '뉴질랜드', region: '오세아니아·태평양', lat: -45.02, lon: 168.74 },
  { code: 'WLG', en: 'Wellington', city: '웰링턴', country: '뉴질랜드', region: '오세아니아·태평양', lat: -41.33, lon: 174.81 },
  { code: 'NAN', en: 'Nadi', city: '난디', country: '피지', region: '오세아니아·태평양', lat: -17.76, lon: 177.44 },
  { code: 'SPN', en: 'Saipan', city: '사이판', country: '미국령 북마리아나', region: '오세아니아·태평양', lat: 15.12, lon: 145.73 },
  { code: 'ROR', en: 'Palau', city: '팔라우', country: '팔라우', region: '오세아니아·태평양', lat: 7.37, lon: 134.54 },
  { code: 'NOU', en: 'Noumea', city: '누메아', country: '뉴칼레도니아', region: '오세아니아·태평양', lat: -22.01, lon: 166.21 },
  { code: 'POM', en: 'Port Moresby', city: '포트모르즈비', country: '파푸아뉴기니', region: '오세아니아·태평양', lat: -9.44, lon: 147.22 },
  { code: 'PPT', en: 'Tahiti', city: '타히티', country: '프랑스령 폴리네시아', region: '오세아니아·태평양', lat: -17.55, lon: -149.61 },
  { code: 'OGG', en: 'Maui', city: '마우이', country: '미국', region: '오세아니아·태평양', lat: 20.90, lon: -156.43 },
  { code: 'KOA', en: 'Kona', city: '코나', country: '미국', region: '오세아니아·태평양', lat: 19.74, lon: -156.05 },
  // 아메리카
  { code: 'ANC', en: 'Anchorage', city: '앵커리지', country: '미국', region: '아메리카', lat: 61.17, lon: -149.99 },
  { code: 'PDX', en: 'Portland', city: '포틀랜드', country: '미국', region: '아메리카', lat: 45.59, lon: -122.60 },
  { code: 'SAN', en: 'San Diego', city: '샌디에이고', country: '미국', region: '아메리카', lat: 32.73, lon: -117.19 },
  { code: 'LAS', en: 'Las Vegas', city: '라스베이거스', country: '미국', region: '아메리카', lat: 36.08, lon: -115.15 },
  { code: 'PHX', en: 'Phoenix', city: '피닉스', country: '미국', region: '아메리카', lat: 33.43, lon: -112.01 },
  { code: 'SLC', en: 'Salt Lake City', city: '솔트레이크시티', country: '미국', region: '아메리카', lat: 40.79, lon: -111.98 },
  { code: 'DEN', en: 'Denver', city: '덴버', country: '미국', region: '아메리카', lat: 39.86, lon: -104.67 },
  { code: 'DFW', en: 'Dallas', city: '댈러스', country: '미국', region: '아메리카', lat: 32.90, lon: -97.04 },
  { code: 'IAH', en: 'Houston', city: '휴스턴', country: '미국', region: '아메리카', lat: 29.99, lon: -95.34 },
  { code: 'MSP', en: 'Minneapolis', city: '미니애폴리스', country: '미국', region: '아메리카', lat: 44.88, lon: -93.22 },
  { code: 'ORD', en: 'Chicago', city: '시카고', country: '미국', region: '아메리카', lat: 41.98, lon: -87.90 },
  { code: 'DTW', en: 'Detroit', city: '디트로이트', country: '미국', region: '아메리카', lat: 42.21, lon: -83.35 },
  { code: 'ATL', en: 'Atlanta', city: '애틀랜타', country: '미국', region: '아메리카', lat: 33.64, lon: -84.43 },
  { code: 'MCO', en: 'Orlando', city: '올랜도', country: '미국', region: '아메리카', lat: 28.43, lon: -81.31 },
  { code: 'MIA', en: 'Miami', city: '마이애미', country: '미국', region: '아메리카', lat: 25.80, lon: -80.29 },
  { code: 'IAD', en: 'Washington', city: '워싱턴 D.C.', country: '미국', region: '아메리카', lat: 38.95, lon: -77.46 },
  { code: 'PHL', en: 'Philadelphia', city: '필라델피아', country: '미국', region: '아메리카', lat: 39.87, lon: -75.24 },
  { code: 'EWR', en: 'Newark', city: '뉴어크', country: '미국', region: '아메리카', lat: 40.69, lon: -74.17 },
  { code: 'BOS', en: 'Boston', city: '보스턴', country: '미국', region: '아메리카', lat: 42.37, lon: -71.01 },
  { code: 'YYC', en: 'Calgary', city: '캘거리', country: '캐나다', region: '아메리카', lat: 51.13, lon: -114.01 },
  { code: 'YYZ', en: 'Toronto', city: '토론토', country: '캐나다', region: '아메리카', lat: 43.68, lon: -79.63 },
  { code: 'YUL', en: 'Montreal', city: '몬트리올', country: '캐나다', region: '아메리카', lat: 45.47, lon: -73.74 },
  { code: 'MEX', en: 'Mexico City', city: '멕시코시티', country: '멕시코', region: '아메리카', lat: 19.44, lon: -99.07 },
  { code: 'CUN', en: 'Cancun', city: '칸쿤', country: '멕시코', region: '아메리카', lat: 21.04, lon: -86.87 },
  { code: 'HAV', en: 'Havana', city: '아바나', country: '쿠바', region: '아메리카', lat: 22.99, lon: -82.41 },
  { code: 'SJU', en: 'San Juan', city: '산후안', country: '푸에르토리코', region: '아메리카', lat: 18.44, lon: -66.00 },
  { code: 'PTY', en: 'Panama City', city: '파나마시티', country: '파나마', region: '아메리카', lat: 9.07, lon: -79.38 },
  { code: 'BOG', en: 'Bogota', city: '보고타', country: '콜롬비아', region: '아메리카', lat: 4.70, lon: -74.15 },
  { code: 'UIO', en: 'Quito', city: '키토', country: '에콰도르', region: '아메리카', lat: -0.13, lon: -78.36 },
  { code: 'LIM', en: 'Lima', city: '리마', country: '페루', region: '아메리카', lat: -12.02, lon: -77.11 },
  { code: 'SCL', en: 'Santiago', city: '산티아고', country: '칠레', region: '아메리카', lat: -33.39, lon: -70.79 },
  { code: 'EZE', en: 'Buenos Aires', city: '부에노스아이레스', country: '아르헨티나', region: '아메리카', lat: -34.82, lon: -58.54 },
  { code: 'GIG', en: 'Rio de Janeiro', city: '리우데자네이루', country: '브라질', region: '아메리카', lat: -22.81, lon: -43.25 },
  // 유럽
  { code: 'KEF', en: 'Reykjavik', city: '레이캬비크', country: '아이슬란드', region: '유럽·아프리카', lat: 63.99, lon: -22.61 },
  { code: 'DUB', en: 'Dublin', city: '더블린', country: '아일랜드', region: '유럽·아프리카', lat: 53.42, lon: -6.27 },
  { code: 'EDI', en: 'Edinburgh', city: '에든버러', country: '영국', region: '유럽·아프리카', lat: 55.95, lon: -3.37 },
  { code: 'MAN', en: 'Manchester', city: '맨체스터', country: '영국', region: '유럽·아프리카', lat: 53.35, lon: -2.28 },
  { code: 'LIS', en: 'Lisbon', city: '리스본', country: '포르투갈', region: '유럽·아프리카', lat: 38.77, lon: -9.13 },
  { code: 'MAD', en: 'Madrid', city: '마드리드', country: '스페인', region: '유럽·아프리카', lat: 40.49, lon: -3.57 },
  { code: 'AGP', en: 'Malaga', city: '말라가', country: '스페인', region: '유럽·아프리카', lat: 36.67, lon: -4.50 },
  { code: 'PMI', en: 'Palma de Mallorca', city: '팔마 데 마요르카', country: '스페인', region: '유럽·아프리카', lat: 39.55, lon: 2.74 },
  { code: 'NCE', en: 'Nice', city: '니스', country: '프랑스', region: '유럽·아프리카', lat: 43.66, lon: 7.21 },
  { code: 'BRU', en: 'Brussels', city: '브뤼셀', country: '벨기에', region: '유럽·아프리카', lat: 50.90, lon: 4.48 },
  { code: 'GVA', en: 'Geneva', city: '제네바', country: '스위스', region: '유럽·아프리카', lat: 46.24, lon: 6.11 },
  { code: 'DUS', en: 'Dusseldorf', city: '뒤셀도르프', country: '독일', region: '유럽·아프리카', lat: 51.29, lon: 6.77 },
  { code: 'HAM', en: 'Hamburg', city: '함부르크', country: '독일', region: '유럽·아프리카', lat: 53.63, lon: 9.99 },
  { code: 'MUC', en: 'Munich', city: '뮌헨', country: '독일', region: '유럽·아프리카', lat: 48.35, lon: 11.79 },
  { code: 'BER', en: 'Berlin', city: '베를린', country: '독일', region: '유럽·아프리카', lat: 52.37, lon: 13.50 },
  { code: 'CPH', en: 'Copenhagen', city: '코펜하겐', country: '덴마크', region: '유럽·아프리카', lat: 55.62, lon: 12.66 },
  { code: 'OSL', en: 'Oslo', city: '오슬로', country: '노르웨이', region: '유럽·아프리카', lat: 60.19, lon: 11.10 },
  { code: 'ARN', en: 'Stockholm', city: '스톡홀름', country: '스웨덴', region: '유럽·아프리카', lat: 59.65, lon: 17.92 },
  { code: 'TLL', en: 'Tallinn', city: '탈린', country: '에스토니아', region: '유럽·아프리카', lat: 59.41, lon: 24.83 },
  { code: 'RIX', en: 'Riga', city: '리가', country: '라트비아', region: '유럽·아프리카', lat: 56.92, lon: 23.97 },
  { code: 'VNO', en: 'Vilnius', city: '빌뉴스', country: '리투아니아', region: '유럽·아프리카', lat: 54.63, lon: 25.29 },
  { code: 'WAW', en: 'Warsaw', city: '바르샤바', country: '폴란드', region: '유럽·아프리카', lat: 52.17, lon: 20.97 },
  { code: 'VIE', en: 'Vienna', city: '빈', country: '오스트리아', region: '유럽·아프리카', lat: 48.11, lon: 16.57 },
  { code: 'BUD', en: 'Budapest', city: '부다페스트', country: '헝가리', region: '유럽·아프리카', lat: 47.44, lon: 19.26 },
  { code: 'ZAG', en: 'Zagreb', city: '자그레브', country: '크로아티아', region: '유럽·아프리카', lat: 45.74, lon: 16.07 },
  { code: 'DBV', en: 'Dubrovnik', city: '두브로브니크', country: '크로아티아', region: '유럽·아프리카', lat: 42.56, lon: 18.27 },
  { code: 'OTP', en: 'Bucharest', city: '부쿠레슈티', country: '루마니아', region: '유럽·아프리카', lat: 44.57, lon: 26.10 },
  { code: 'MXP', en: 'Milan', city: '밀라노', country: '이탈리아', region: '유럽·아프리카', lat: 45.63, lon: 8.72 },
  { code: 'VCE', en: 'Venice', city: '베네치아', country: '이탈리아', region: '유럽·아프리카', lat: 45.51, lon: 12.35 },
  { code: 'NAP', en: 'Naples', city: '나폴리', country: '이탈리아', region: '유럽·아프리카', lat: 40.88, lon: 14.29 },
  { code: 'MLA', en: 'Malta', city: '몰타', country: '몰타', region: '유럽·아프리카', lat: 35.86, lon: 14.48 },
  { code: 'ATH', en: 'Athens', city: '아테네', country: '그리스', region: '유럽·아프리카', lat: 37.94, lon: 23.94 },
  // 아프리카
  { code: 'CMN', en: 'Casablanca', city: '카사블랑카', country: '모로코', region: '유럽·아프리카', lat: 33.37, lon: -7.59 },
  { code: 'RAK', en: 'Marrakesh', city: '마라케시', country: '모로코', region: '유럽·아프리카', lat: 31.61, lon: -8.04 },
  { code: 'TUN', en: 'Tunis', city: '튀니스', country: '튀니지', region: '유럽·아프리카', lat: 36.85, lon: 10.23 },
  { code: 'HRG', en: 'Hurghada', city: '후르가다', country: '이집트', region: '유럽·아프리카', lat: 27.18, lon: 33.80 },
  { code: 'ADD', en: 'Addis Ababa', city: '아디스아바바', country: '에티오피아', region: '유럽·아프리카', lat: 8.98, lon: 38.80 },
  { code: 'NBO', en: 'Nairobi', city: '나이로비', country: '케냐', region: '유럽·아프리카', lat: -1.32, lon: 36.93 },
  { code: 'DAR', en: 'Dar es Salaam', city: '다르에스살람', country: '탄자니아', region: '유럽·아프리카', lat: -6.88, lon: 39.20 },
  { code: 'ZNZ', en: 'Zanzibar', city: '잔지바르', country: '탄자니아', region: '유럽·아프리카', lat: -6.22, lon: 39.22 },
  { code: 'LOS', en: 'Lagos', city: '라고스', country: '나이지리아', region: '유럽·아프리카', lat: 6.58, lon: 3.32 },
  { code: 'ACC', en: 'Accra', city: '아크라', country: '가나', region: '유럽·아프리카', lat: 5.61, lon: -0.17 },
  { code: 'CPT', en: 'Cape Town', city: '케이프타운', country: '남아프리카공화국', region: '유럽·아프리카', lat: -33.96, lon: 18.60 },
  { code: 'MRU', en: 'Mauritius', city: '모리셔스', country: '모리셔스', region: '유럽·아프리카', lat: -20.43, lon: 57.68 },
  { code: 'SEZ', en: 'Seychelles', city: '세이셸', country: '세이셸', region: '유럽·아프리카', lat: -4.67, lon: 55.52 },
  // 인천에서 1시간 안팎
  { code: 'OSN', en: 'Osan', city: '오산', country: '대한민국', region: '한국', lat: 37.09, lon: 127.03 },
  { code: 'HMY', en: 'Seosan', city: '서산', country: '대한민국', region: '한국', lat: 36.70, lon: 126.49 },
  { code: 'YEC', en: 'Yecheon', city: '예천', country: '대한민국', region: '한국', lat: 36.63, lon: 128.35 },
  { code: 'KAG', en: 'Gangneung', city: '강릉', country: '대한민국', region: '한국', lat: 37.75, lon: 128.94 },
  { code: 'SHO', en: 'Sokcho', city: '속초', country: '대한민국', region: '한국', lat: 38.14, lon: 128.60 },
  { code: 'MPK', en: 'Mokpo', city: '목포', country: '대한민국', region: '한국', lat: 34.76, lon: 126.38 },
  { code: 'JDG', en: 'Jeongseok', city: '제주 정석', country: '대한민국', region: '한국', lat: 33.40, lon: 126.71 },
  { code: 'FNJ', en: 'Pyongyang', city: '평양', country: '북한', region: '한국', lat: 39.22, lon: 125.67 },
  { code: 'WOS', en: 'Wonsan', city: '원산', country: '북한', region: '한국', lat: 39.17, lon: 127.49 },
  { code: 'WEH', en: 'Weihai', city: '웨이하이', country: '중국', region: '중화권', lat: 37.19, lon: 122.23 },
  { code: 'YNT', en: 'Yantai', city: '옌타이', country: '중국', region: '중화권', lat: 37.66, lon: 120.99 },
  { code: 'DDG', en: 'Dandong', city: '단둥', country: '중국', region: '중화권', lat: 40.02, lon: 124.29 },
  { code: 'TSJ', en: 'Tsushima', city: '쓰시마', country: '일본', region: '일본', lat: 34.28, lon: 129.33 },
  { code: 'IKI', en: 'Iki', city: '이키', country: '일본', region: '일본', lat: 33.75, lon: 129.79 },
  { code: 'FUJ', en: 'Goto Fukue', city: '고토 후쿠에', country: '일본', region: '일본', lat: 32.67, lon: 128.83 },
  // 일본 더
  { code: 'HSG', en: 'Saga', city: '사가', country: '일본', region: '일본', lat: 33.15, lon: 130.30 },
  { code: 'UBJ', en: 'Yamaguchi Ube', city: '야마구치 우베', country: '일본', region: '일본', lat: 33.93, lon: 131.28 },
  { code: 'IZO', en: 'Izumo', city: '이즈모', country: '일본', region: '일본', lat: 35.41, lon: 132.89 },
  { code: 'YGJ', en: 'Yonago', city: '요나고', country: '일본', region: '일본', lat: 35.49, lon: 133.24 },
  { code: 'KMI', en: 'Miyazaki', city: '미야자키', country: '일본', region: '일본', lat: 31.88, lon: 131.45 },
  { code: 'KCZ', en: 'Kochi', city: '고치', country: '일본', region: '일본', lat: 33.55, lon: 133.67 },
  { code: 'TKS', en: 'Tokushima', city: '도쿠시마', country: '일본', region: '일본', lat: 34.13, lon: 134.61 },
  { code: 'UKB', en: 'Kobe', city: '고베', country: '일본', region: '일본', lat: 34.63, lon: 135.22 },
  { code: 'TOY', en: 'Toyama', city: '도야마', country: '일본', region: '일본', lat: 36.65, lon: 137.19 },
  { code: 'AXT', en: 'Akita', city: '아키타', country: '일본', region: '일본', lat: 39.62, lon: 140.22 },
  { code: 'AKJ', en: 'Asahikawa', city: '아사히카와', country: '일본', region: '일본', lat: 43.67, lon: 142.45 },
  // 중국 더
  { code: 'TNA', en: 'Jinan', city: '지난', country: '중국', region: '중화권', lat: 36.86, lon: 117.22 },
  { code: 'SJW', en: 'Shijiazhuang', city: '스자좡', country: '중국', region: '중화권', lat: 38.28, lon: 114.70 },
  { code: 'CGQ', en: 'Changchun', city: '창춘', country: '중국', region: '중화권', lat: 43.99, lon: 125.69 },
  { code: 'MDG', en: 'Mudanjiang', city: '무단장', country: '중국', region: '중화권', lat: 44.52, lon: 129.57 },
  { code: 'WUX', en: 'Wuxi', city: '우시', country: '중국', region: '중화권', lat: 31.49, lon: 120.43 },
  { code: 'NGB', en: 'Ningbo', city: '닝보', country: '중국', region: '중화권', lat: 29.83, lon: 121.46 },
  { code: 'FOC', en: 'Fuzhou', city: '푸저우', country: '중국', region: '중화권', lat: 25.94, lon: 119.66 },
  { code: 'KWL', en: 'Guilin', city: '구이린', country: '중국', region: '중화권', lat: 25.22, lon: 110.04 },
  { code: 'DYG', en: 'Zhangjiajie', city: '장자제', country: '중국', region: '중화권', lat: 29.10, lon: 110.44 },
  // 동남아시아 더
  { code: 'DLI', en: 'Da Lat', city: '달랏', country: '베트남', region: '동남아시아', lat: 11.75, lon: 108.37 },
  { code: 'HUI', en: 'Hue', city: '후에', country: '베트남', region: '동남아시아', lat: 16.40, lon: 107.70 },
  { code: 'KBV', en: 'Krabi', city: '끄라비', country: '태국', region: '동남아시아', lat: 8.10, lon: 98.99 },
  { code: 'USM', en: 'Koh Samui', city: '코사무이', country: '태국', region: '동남아시아', lat: 9.55, lon: 100.06 },
  { code: 'TAG', en: 'Bohol', city: '보홀', country: '필리핀', region: '동남아시아', lat: 9.57, lon: 123.78 },
  { code: 'PPS', en: 'Puerto Princesa', city: '팔라완', country: '필리핀', region: '동남아시아', lat: 9.74, lon: 118.76 },
  { code: 'YIA', en: 'Yogyakarta', city: '족자카르타', country: '인도네시아', region: '동남아시아', lat: -7.90, lon: 110.06 },
  { code: 'LOP', en: 'Lombok', city: '롬복', country: '인도네시아', region: '동남아시아', lat: -8.76, lon: 116.28 },
  // ---- OurAirports 데이터(퍼블릭 도메인)에서 추가: 정기편 대형 공항 + 한국에서 2,000km 안의 중형 공항. 좌표는 데이터 그대로, 한글 이름은 직접 붙임 ----
  { code: 'HIR', en: 'Honiara', city: '호니아라', country: '솔로몬 제도', region: '오세아니아·태평양', lat: -9.43, lon: 160.05 },
  { code: 'YEG', en: 'Edmonton', city: '에드먼턴', country: '캐나다', region: '아메리카', lat: 53.31, lon: -113.58 },
  { code: 'YHZ', en: 'Halifax', city: '핼리팩스', country: '캐나다', region: '아메리카', lat: 44.88, lon: -63.51 },
  { code: 'YOW', en: 'Ottawa', city: '오타와', country: '캐나다', region: '아메리카', lat: 45.32, lon: -75.67 },
  { code: 'YQB', en: 'Quebec City', city: '퀘벡시티', country: '캐나다', region: '아메리카', lat: 46.79, lon: -71.39 },
  { code: 'YWG', en: 'Winnipeg', city: '위니펙', country: '캐나다', region: '아메리카', lat: 49.91, lon: -97.24 },
  { code: 'YXS', en: 'Prince George', city: '프린스조지', country: '캐나다', region: '아메리카', lat: 53.88, lon: -122.67 },
  { code: 'YXX', en: 'Abbotsford', city: '애버츠퍼드', country: '캐나다', region: '아메리카', lat: 49.03, lon: -122.36 },
  { code: 'YYJ', en: 'Victoria', city: '빅토리아', country: '캐나다', region: '아메리카', lat: 48.65, lon: -123.43 },
  { code: 'YYT', en: 'St. John\'s', city: '세인트존스', country: '캐나다', region: '아메리카', lat: 47.62, lon: -52.75 },
  { code: 'ALG', en: 'Algiers', city: '알제', country: '알제리', region: '유럽·아프리카', lat: 36.69, lon: 3.21 },
  { code: 'ABV', en: 'Abuja', city: '아부자', country: '나이지리아', region: '유럽·아프리카', lat: 9.01, lon: 7.26 },
  { code: 'NIM', en: 'Niamey', city: '니아메', country: '니제르', region: '유럽·아프리카', lat: 13.48, lon: 2.18 },
  { code: 'CGN', en: 'Cologne Bonn', city: '쾰른·본', country: '독일', region: '유럽·아프리카', lat: 50.87, lon: 7.14 },
  { code: 'NUE', en: 'Nuremberg', city: '뉘른베르크', country: '독일', region: '유럽·아프리카', lat: 49.5, lon: 11.08 },
  { code: 'LEJ', en: 'Leipzig', city: '라이프치히', country: '독일', region: '유럽·아프리카', lat: 51.42, lon: 12.24 },
  { code: 'STR', en: 'Stuttgart', city: '슈투트가르트', country: '독일', region: '유럽·아프리카', lat: 48.69, lon: 9.22 },
  { code: 'HAJ', en: 'Hanover', city: '하노버', country: '독일', region: '유럽·아프리카', lat: 52.46, lon: 9.69 },
  { code: 'BFS', en: 'Belfast', city: '벨파스트', country: '영국', region: '유럽·아프리카', lat: 54.66, lon: -6.22 },
  { code: 'BHX', en: 'Birmingham', city: '버밍엄', country: '영국', region: '유럽·아프리카', lat: 52.45, lon: -1.75 },
  { code: 'LTN', en: 'London Luton', city: '런던 루턴', country: '영국', region: '유럽·아프리카', lat: 51.87, lon: -0.37 },
  { code: 'LGW', en: 'London Gatwick', city: '런던 개트윅', country: '영국', region: '유럽·아프리카', lat: 51.15, lon: -0.19 },
  { code: 'GLA', en: 'Glasgow', city: '글래스고', country: '영국', region: '유럽·아프리카', lat: 55.87, lon: -4.43 },
  { code: 'STN', en: 'London Stansted', city: '런던 스탠스테드', country: '영국', region: '유럽·아프리카', lat: 51.88, lon: 0.23 },
  { code: 'EIN', en: 'Eindhoven', city: '에인트호번', country: '네덜란드', region: '유럽·아프리카', lat: 51.45, lon: 5.37 },
  { code: 'EHU', en: 'Ezhou', city: '어저우', country: '중국', region: '중화권', lat: 30.34, lon: 115.04 },
  { code: 'SNN', en: 'Shannon', city: '섀넌', country: '아일랜드', region: '유럽·아프리카', lat: 52.7, lon: -8.92 },
  { code: 'BLL', en: 'Billund', city: '빌룬', country: '덴마크', region: '유럽·아프리카', lat: 55.74, lon: 9.15 },
  { code: 'LUX', en: 'Luxembourg', city: '룩셈부르크', country: '룩셈부르크', region: '유럽·아프리카', lat: 49.62, lon: 6.2 },
  { code: 'BGO', en: 'Bergen', city: '베르겐', country: '노르웨이', region: '유럽·아프리카', lat: 60.29, lon: 5.22 },
  { code: 'TOS', en: 'Tromso', city: '트롬쇠', country: '노르웨이', region: '유럽·아프리카', lat: 69.68, lon: 18.92 },
  { code: 'TRD', en: 'Trondheim', city: '트론헤임', country: '노르웨이', region: '유럽·아프리카', lat: 63.46, lon: 10.92 },
  { code: 'SVG', en: 'Stavanger', city: '스타방에르', country: '노르웨이', region: '유럽·아프리카', lat: 58.88, lon: 5.64 },
  { code: 'GDN', en: 'Gdansk', city: '그단스크', country: '폴란드', region: '유럽·아프리카', lat: 54.38, lon: 18.47 },
  { code: 'KRK', en: 'Krakow', city: '크라쿠프', country: '폴란드', region: '유럽·아프리카', lat: 50.08, lon: 19.78 },
  { code: 'GOT', en: 'Gothenburg', city: '예테보리', country: '스웨덴', region: '유럽·아프리카', lat: 57.66, lon: 12.28 },
  { code: 'DUR', en: 'Durban', city: '더반', country: '남아프리카', region: '유럽·아프리카', lat: -29.61, lon: 31.12 },
  { code: 'GBE', en: 'Gaborone', city: '가보로네', country: '보츠와나', region: '유럽·아프리카', lat: -24.56, lon: 25.92 },
  { code: 'LUN', en: 'Lusaka', city: '루사카', country: '잠비아', region: '유럽·아프리카', lat: -15.33, lon: 28.45 },
  { code: 'RUN', en: 'Reunion', city: '레위니옹', country: '레위니옹', region: '유럽·아프리카', lat: -20.89, lon: 55.52 },
  { code: 'TNR', en: 'Antananarivo', city: '안타나나리보', country: '마다가스카르', region: '유럽·아프리카', lat: -18.8, lon: 47.48 },
  { code: 'LAD', en: 'Luanda', city: '루안다', country: '앙골라', region: '유럽·아프리카', lat: -8.86, lon: 13.23 },
  { code: 'MPM', en: 'Maputo', city: '마푸투', country: '모잠비크', region: '유럽·아프리카', lat: -25.92, lon: 32.57 },
  { code: 'NDJ', en: 'N\'Djamena', city: '은자메나', country: '차드', region: '유럽·아프리카', lat: 12.13, lon: 15.03 },
  { code: 'HRE', en: 'Harare', city: '하라레', country: '짐바브웨', region: '유럽·아프리카', lat: -17.93, lon: 31.09 },
  { code: 'WDH', en: 'Windhoek', city: '빈트후크', country: '나미비아', region: '유럽·아프리카', lat: -22.48, lon: 17.47 },
  { code: 'FIH', en: 'Kinshasa', city: '킨샤사', country: '콩고-킨샤사', region: '유럽·아프리카', lat: -4.39, lon: 15.44 },
  { code: 'BKO', en: 'Bamako', city: '바마코', country: '말리', region: '유럽·아프리카', lat: 12.53, lon: -7.95 },
  { code: 'BJL', en: 'Banjul', city: '반줄', country: '감비아', region: '유럽·아프리카', lat: 13.34, lon: -16.65 },
  { code: 'FUE', en: 'Fuerteventura', city: '푸에르테벤투라', country: '스페인', region: '유럽·아프리카', lat: 28.45, lon: -13.86 },
  { code: 'LPA', en: 'Gran Canaria', city: '그란카나리아', country: '스페인', region: '유럽·아프리카', lat: 27.93, lon: -15.39 },
  { code: 'ACE', en: 'Lanzarote', city: '란사로테', country: '스페인', region: '유럽·아프리카', lat: 28.95, lon: -13.61 },
  { code: 'TFS', en: 'Tenerife', city: '테네리페', country: '스페인', region: '유럽·아프리카', lat: 28.04, lon: -16.57 },
  { code: 'FNA', en: 'Freetown', city: '프리타운', country: '시에라리온', region: '유럽·아프리카', lat: 8.62, lon: -13.2 },
  { code: 'ROB', en: 'Monrovia', city: '몬로비아', country: '라이베리아', region: '유럽·아프리카', lat: 6.23, lon: -10.36 },
  { code: 'DSS', en: 'Dakar', city: '다카르', country: '세네갈', region: '유럽·아프리카', lat: 14.67, lon: -17.07 },
  { code: 'NKC', en: 'Nouakchott', city: '누악쇼트', country: '모리타니', region: '유럽·아프리카', lat: 18.31, lon: -15.97 },
  { code: 'SID', en: 'Sal Island', city: '살섬', country: '카보베르데', region: '유럽·아프리카', lat: 16.74, lon: -22.95 },
  { code: 'JIB', en: 'Djibouti', city: '지부티', country: '지부티', region: '유럽·아프리카', lat: 11.55, lon: 43.16 },
  { code: 'SSH', en: 'Sharm El Sheikh', city: '샤름엘셰이크', country: '이집트', region: '유럽·아프리카', lat: 27.98, lon: 34.39 },
  { code: 'JUB', en: 'Juba', city: '주바', country: '남수단', region: '유럽·아프리카', lat: 4.87, lon: 31.6 },
  { code: 'MBA', en: 'Mombasa', city: '몸바사', country: '케냐', region: '유럽·아프리카', lat: -4.03, lon: 39.59 },
  { code: 'MJI', en: 'Tripoli', city: '트리폴리', country: '리비아', region: '유럽·아프리카', lat: 32.89, lon: 13.29 },
  { code: 'KGL', en: 'Kigali', city: '키갈리', country: '르완다', region: '유럽·아프리카', lat: -1.97, lon: 30.14 },
  { code: 'KRT', en: 'Khartoum', city: '하르툼', country: '수단', region: '유럽·아프리카', lat: 15.59, lon: 32.55 },
  { code: 'EBB', en: 'Entebbe', city: '엔테베', country: '우간다', region: '유럽·아프리카', lat: 0.04, lon: 32.44 },
  { code: 'AUS', en: 'Austin', city: '오스틴', country: '미국', region: '아메리카', lat: 30.2, lon: -97.66 },
  { code: 'BNA', en: 'Nashville', city: '내슈빌', country: '미국', region: '아메리카', lat: 36.12, lon: -86.68 },
  { code: 'BUF', en: 'Buffalo', city: '버펄로', country: '미국', region: '아메리카', lat: 42.94, lon: -78.73 },
  { code: 'BWI', en: 'Baltimore', city: '볼티모어', country: '미국', region: '아메리카', lat: 39.18, lon: -76.67 },
  { code: 'CLE', en: 'Cleveland', city: '클리블랜드', country: '미국', region: '아메리카', lat: 41.41, lon: -81.85 },
  { code: 'CLT', en: 'Charlotte', city: '샬럿', country: '미국', region: '아메리카', lat: 35.21, lon: -80.94 },
  { code: 'CMH', en: 'Columbus', city: '콜럼버스', country: '미국', region: '아메리카', lat: 40, lon: -82.89 },
  { code: 'CVG', en: 'Cincinnati', city: '신시내티', country: '미국', region: '아메리카', lat: 39.05, lon: -84.67 },
  { code: 'DCA', en: 'Washington National', city: '워싱턴 레이건', country: '미국', region: '아메리카', lat: 38.85, lon: -77.04 },
  { code: 'FLL', en: 'Fort Lauderdale', city: '포트로더데일', country: '미국', region: '아메리카', lat: 26.07, lon: -80.15 },
  { code: 'IND', en: 'Indianapolis', city: '인디애나폴리스', country: '미국', region: '아메리카', lat: 39.72, lon: -86.29 },
  { code: 'JAX', en: 'Jacksonville', city: '잭슨빌', country: '미국', region: '아메리카', lat: 30.49, lon: -81.69 },
  { code: 'LGA', en: 'New York LaGuardia', city: '뉴욕 라과디아', country: '미국', region: '아메리카', lat: 40.78, lon: -73.87 },
  { code: 'MCI', en: 'Kansas City', city: '캔자스시티', country: '미국', region: '아메리카', lat: 39.3, lon: -94.71 },
  { code: 'MDW', en: 'Chicago Midway', city: '시카고 미드웨이', country: '미국', region: '아메리카', lat: 41.79, lon: -87.75 },
  { code: 'MEM', en: 'Memphis', city: '멤피스', country: '미국', region: '아메리카', lat: 35.04, lon: -89.98 },
  { code: 'MKE', en: 'Milwaukee', city: '밀워키', country: '미국', region: '아메리카', lat: 42.95, lon: -87.9 },
  { code: 'MSY', en: 'New Orleans', city: '뉴올리언스', country: '미국', region: '아메리카', lat: 29.99, lon: -90.26 },
  { code: 'OAK', en: 'Oakland', city: '오클랜드(미국)', country: '미국', region: '아메리카', lat: 37.72, lon: -122.22 },
  { code: 'ONT', en: 'Ontario California', city: '온타리오(캘리포니아)', country: '미국', region: '아메리카', lat: 34.06, lon: -117.6 },
  { code: 'PBI', en: 'West Palm Beach', city: '웨스트팜비치', country: '미국', region: '아메리카', lat: 26.68, lon: -80.1 },
  { code: 'PIT', en: 'Pittsburgh', city: '피츠버그', country: '미국', region: '아메리카', lat: 40.49, lon: -80.23 },
  { code: 'PWM', en: 'Portland Maine', city: '포틀랜드(메인)', country: '미국', region: '아메리카', lat: 43.65, lon: -70.31 },
  { code: 'PVD', en: 'Providence', city: '프로비던스', country: '미국', region: '아메리카', lat: 41.73, lon: -71.43 },
  { code: 'RDU', en: 'Raleigh Durham', city: '롤리·더럼', country: '미국', region: '아메리카', lat: 35.88, lon: -78.79 },
  { code: 'RIC', en: 'Richmond', city: '리치먼드', country: '미국', region: '아메리카', lat: 37.51, lon: -77.32 },
  { code: 'RNO', en: 'Reno', city: '리노', country: '미국', region: '아메리카', lat: 39.5, lon: -119.77 },
  { code: 'RSW', en: 'Fort Myers', city: '포트마이어스', country: '미국', region: '아메리카', lat: 26.54, lon: -81.76 },
  { code: 'SAT', en: 'San Antonio', city: '샌안토니오', country: '미국', region: '아메리카', lat: 29.53, lon: -98.47 },
  { code: 'SAV', en: 'Savannah', city: '서배너', country: '미국', region: '아메리카', lat: 32.13, lon: -81.2 },
  { code: 'SDF', en: 'Louisville', city: '루이빌', country: '미국', region: '아메리카', lat: 38.17, lon: -85.74 },
  { code: 'SFB', en: 'Orlando Sanford', city: '올랜도 샌퍼드', country: '미국', region: '아메리카', lat: 28.78, lon: -81.24 },
  { code: 'SJC', en: 'San Jose', city: '새너제이', country: '미국', region: '아메리카', lat: 37.36, lon: -121.93 },
  { code: 'SMF', en: 'Sacramento', city: '새크라멘토', country: '미국', region: '아메리카', lat: 38.7, lon: -121.59 },
  { code: 'SNA', en: 'Orange County', city: '오렌지카운티', country: '미국', region: '아메리카', lat: 33.68, lon: -117.87 },
  { code: 'STL', en: 'St. Louis', city: '세인트루이스', country: '미국', region: '아메리카', lat: 38.75, lon: -90.37 },
  { code: 'SYR', en: 'Syracuse', city: '시러큐스', country: '미국', region: '아메리카', lat: 43.11, lon: -76.11 },
  { code: 'TPA', en: 'Tampa', city: '탬파', country: '미국', region: '아메리카', lat: 27.98, lon: -82.53 },
  { code: 'TUL', en: 'Tulsa', city: '털사', country: '미국', region: '아메리카', lat: 36.2, lon: -95.89 },
  { code: 'TIA', en: 'Tirana', city: '티라나', country: '알바니아', region: '유럽·아프리카', lat: 41.41, lon: 19.72 },
  { code: 'BOJ', en: 'Burgas', city: '부르가스', country: '불가리아', region: '유럽·아프리카', lat: 42.57, lon: 27.52 },
  { code: 'SOF', en: 'Sofia', city: '소피아', country: '불가리아', region: '유럽·아프리카', lat: 42.7, lon: 23.41 },
  { code: 'VAR', en: 'Varna', city: '바르나', country: '불가리아', region: '유럽·아프리카', lat: 43.23, lon: 27.83 },
  { code: 'LCA', en: 'Larnaca', city: '라르나카', country: '키프로스', region: '아시아·중동', lat: 34.88, lon: 33.62 },
  { code: 'ALC', en: 'Alicante', city: '알리칸테', country: '스페인', region: '유럽·아프리카', lat: 38.28, lon: -0.56 },
  { code: 'IBZ', en: 'Ibiza', city: '이비사', country: '스페인', region: '유럽·아프리카', lat: 38.87, lon: 1.37 },
  { code: 'SCQ', en: 'Santiago de Compostela', city: '산티아고데콤포스텔라', country: '스페인', region: '유럽·아프리카', lat: 42.9, lon: -8.42 },
  { code: 'BOD', en: 'Bordeaux', city: '보르도', country: '프랑스', region: '유럽·아프리카', lat: 44.83, lon: -0.72 },
  { code: 'TLS', en: 'Toulouse', city: '툴루즈', country: '프랑스', region: '유럽·아프리카', lat: 43.63, lon: 1.36 },
  { code: 'LYS', en: 'Lyon', city: '리옹', country: '프랑스', region: '유럽·아프리카', lat: 45.73, lon: 5.08 },
  { code: 'MRS', en: 'Marseille', city: '마르세유', country: '프랑스', region: '유럽·아프리카', lat: 43.44, lon: 5.22 },
  { code: 'ORY', en: 'Paris Orly', city: '파리 오를리', country: '프랑스', region: '유럽·아프리카', lat: 48.72, lon: 2.38 },
  { code: 'BSL', en: 'Basel Mulhouse', city: '바젤·뮐루즈', country: '프랑스', region: '유럽·아프리카', lat: 47.59, lon: 7.53 },
  { code: 'HER', en: 'Heraklion', city: '이라클리오', country: '그리스', region: '유럽·아프리카', lat: 35.34, lon: 25.18 },
  { code: 'SKG', en: 'Thessaloniki', city: '테살로니키', country: '그리스', region: '유럽·아프리카', lat: 40.52, lon: 22.97 },
  { code: 'BRI', en: 'Bari', city: '바리', country: '이탈리아', region: '유럽·아프리카', lat: 41.14, lon: 16.76 },
  { code: 'BDS', en: 'Brindisi', city: '브린디시', country: '이탈리아', region: '유럽·아프리카', lat: 40.66, lon: 17.95 },
  { code: 'CTA', en: 'Catania', city: '카타니아', country: '이탈리아', region: '유럽·아프리카', lat: 37.47, lon: 15.07 },
  { code: 'PMO', en: 'Palermo', city: '팔레르모', country: '이탈리아', region: '유럽·아프리카', lat: 38.18, lon: 13.09 },
  { code: 'CAG', en: 'Cagliari', city: '칼리아리', country: '이탈리아', region: '유럽·아프리카', lat: 39.25, lon: 9.05 },
  { code: 'BGY', en: 'Milan Bergamo', city: '밀라노 베르가모', country: '이탈리아', region: '유럽·아프리카', lat: 45.67, lon: 9.7 },
  { code: 'TRN', en: 'Turin', city: '토리노', country: '이탈리아', region: '유럽·아프리카', lat: 45.2, lon: 7.65 },
  { code: 'BLQ', en: 'Bologna', city: '볼로냐', country: '이탈리아', region: '유럽·아프리카', lat: 44.54, lon: 11.29 },
  { code: 'VRN', en: 'Verona', city: '베로나', country: '이탈리아', region: '유럽·아프리카', lat: 45.39, lon: 10.89 },
  { code: 'PSA', en: 'Pisa', city: '피사', country: '이탈리아', region: '유럽·아프리카', lat: 43.68, lon: 10.39 },
  { code: 'LJU', en: 'Ljubljana', city: '류블랴나', country: '슬로베니아', region: '유럽·아프리카', lat: 46.22, lon: 14.46 },
  { code: 'ETM', en: 'Eilat', city: '에일라트', country: '이스라엘', region: '아시아·중동', lat: 29.73, lon: 35.01 },
  { code: 'FAO', en: 'Faro', city: '파루', country: '포르투갈', region: '유럽·아프리카', lat: 37.01, lon: -7.97 },
  { code: 'PDL', en: 'Ponta Delgada', city: '폰타델가다', country: '포르투갈', region: '유럽·아프리카', lat: 37.74, lon: -25.7 },
  { code: 'OPO', en: 'Porto', city: '포르투', country: '포르투갈', region: '유럽·아프리카', lat: 41.25, lon: -8.68 },
  { code: 'ESB', en: 'Ankara', city: '앙카라', country: '튀르키예', region: '아시아·중동', lat: 40.13, lon: 33 },
  { code: 'ADB', en: 'Izmir', city: '이즈미르', country: '튀르키예', region: '아시아·중동', lat: 38.29, lon: 27.16 },
  { code: 'DLM', en: 'Dalaman', city: '달라만', country: '튀르키예', region: '아시아·중동', lat: 36.71, lon: 28.79 },
  { code: 'BJV', en: 'Bodrum', city: '보드룸', country: '튀르키예', region: '아시아·중동', lat: 37.25, lon: 27.66 },
  { code: 'SKP', en: 'Skopje', city: '스코페', country: '북마케도니아', region: '유럽·아프리카', lat: 41.96, lon: 21.62 },
  { code: 'BEG', en: 'Belgrade', city: '베오그라드', country: '세르비아', region: '유럽·아프리카', lat: 44.82, lon: 20.31 },
  { code: 'TGD', en: 'Podgorica', city: '포드고리차', country: '몬테네그로', region: '유럽·아프리카', lat: 42.36, lon: 19.25 },
  { code: 'BTS', en: 'Bratislava', city: '브라티슬라바', country: '슬로바키아', region: '유럽·아프리카', lat: 48.17, lon: 17.21 },
  { code: 'PLS', en: 'Providenciales', city: '프로비덴시알레스', country: '터크스 케이커스 제도', region: '아메리카', lat: 21.77, lon: -72.27 },
  { code: 'PUJ', en: 'Punta Cana', city: '푼타카나', country: '도미니카 공화국', region: '아메리카', lat: 18.57, lon: -68.36 },
  { code: 'SDQ', en: 'Santo Domingo', city: '산토도밍고', country: '도미니카 공화국', region: '아메리카', lat: 18.43, lon: -69.67 },
  { code: 'GUA', en: 'Guatemala City', city: '과테말라시티', country: '과테말라', region: '아메리카', lat: 14.58, lon: -90.53 },
  { code: 'KIN', en: 'Kingston', city: '킹스턴', country: '자메이카', region: '아메리카', lat: 17.94, lon: -76.79 },
  { code: 'ACA', en: 'Acapulco', city: '아카풀코', country: '멕시코', region: '아메리카', lat: 16.76, lon: -99.76 },
  { code: 'CZM', en: 'Cozumel', city: '코수멜', country: '멕시코', region: '아메리카', lat: 20.51, lon: -86.93 },
  { code: 'DGO', en: 'Durango', city: '두랑고', country: '멕시코', region: '아메리카', lat: 24.13, lon: -104.53 },
  { code: 'GDL', en: 'Guadalajara', city: '과달라하라', country: '멕시코', region: '아메리카', lat: 20.53, lon: -103.3 },
  { code: 'HMO', en: 'Hermosillo', city: '에르모시요', country: '멕시코', region: '아메리카', lat: 29.1, lon: -111.05 },
  { code: 'BJX', en: 'Leon Bajio', city: '레온(바히오)', country: '멕시코', region: '아메리카', lat: 20.99, lon: -101.48 },
  { code: 'MID', en: 'Merida', city: '메리다', country: '멕시코', region: '아메리카', lat: 20.93, lon: -89.66 },
  { code: 'MTY', en: 'Monterrey', city: '몬테레이', country: '멕시코', region: '아메리카', lat: 25.78, lon: -100.11 },
  { code: 'MZT', en: 'Mazatlan', city: '마사틀란', country: '멕시코', region: '아메리카', lat: 23.17, lon: -106.27 },
  { code: 'PVR', en: 'Puerto Vallarta', city: '푸에르토바야르타', country: '멕시코', region: '아메리카', lat: 20.68, lon: -105.25 },
  { code: 'SJD', en: 'Los Cabos', city: '로스카보스', country: '멕시코', region: '아메리카', lat: 23.16, lon: -109.72 },
  { code: 'NLU', en: 'Mexico City Felipe Angeles', city: '멕시코시티 펠리페앙헬레스', country: '멕시코', region: '아메리카', lat: 19.75, lon: -99.01 },
  { code: 'TIJ', en: 'Tijuana', city: '티후아나', country: '멕시코', region: '아메리카', lat: 32.55, lon: -116.98 },
  { code: 'TLC', en: 'Toluca', city: '톨루카', country: '멕시코', region: '아메리카', lat: 19.34, lon: -99.57 },
  { code: 'LIR', en: 'Liberia', city: '리베리아(코스타리카)', country: '코스타리카', region: '아메리카', lat: 10.59, lon: -85.54 },
  { code: 'SAL', en: 'San Salvador', city: '산살바도르', country: '엘살바도르', region: '아메리카', lat: 13.44, lon: -89.06 },
  { code: 'PAP', en: 'Port-au-Prince', city: '포르토프랭스', country: '아이티', region: '아메리카', lat: 18.58, lon: -72.29 },
  { code: 'VRA', en: 'Varadero', city: '바라데로', country: '쿠바', region: '아메리카', lat: 23.03, lon: -81.44 },
  { code: 'GCM', en: 'Grand Cayman', city: '그랜드케이맨', country: '케이맨 제도', region: '아메리카', lat: 19.29, lon: -81.36 },
  { code: 'NAS', en: 'Nassau', city: '나소', country: '바하마', region: '아메리카', lat: 25.04, lon: -77.47 },
  { code: 'BZE', en: 'Belize City', city: '벨리즈시티', country: '벨리즈', region: '아메리카', lat: 17.54, lon: -88.3 },
  { code: 'VLI', en: 'Port Vila', city: '포트빌라', country: '바누아투', region: '오세아니아·태평양', lat: -17.7, lon: 168.32 },
  { code: 'GEA', en: 'Noumea Magenta', city: '누메아 마젠타', country: '뉴칼레도니아', region: '오세아니아·태평양', lat: -22.26, lon: 166.47 },
  { code: 'DMM', en: 'Dammam', city: '담맘', country: '사우디아라비아', region: '아시아·중동', lat: 26.47, lon: 49.8 },
  { code: 'MED', en: 'Medina', city: '메디나', country: '사우디아라비아', region: '아시아·중동', lat: 24.55, lon: 39.71 },
  { code: 'IKA', en: 'Tehran', city: '테헤란', country: '이란', region: '아시아·중동', lat: 35.42, lon: 51.15 },
  { code: 'THR', en: 'Tehran Mehrabad', city: '테헤란 메흐라바드', country: '이란', region: '아시아·중동', lat: 35.69, lon: 51.31 },
  { code: 'MHD', en: 'Mashhad', city: '마슈하드', country: '이란', region: '아시아·중동', lat: 36.24, lon: 59.64 },
  { code: 'SYZ', en: 'Shiraz', city: '시라즈', country: '이란', region: '아시아·중동', lat: 29.54, lon: 52.59 },
  { code: 'BEY', en: 'Beirut', city: '베이루트', country: '레바논', region: '아시아·중동', lat: 33.82, lon: 35.49 },
  { code: 'DQM', en: 'Duqm', city: '두큼', country: '오만', region: '아시아·중동', lat: 19.5, lon: 57.63 },
  { code: 'DWC', en: 'Dubai Al Maktoum', city: '두바이 알막툼', country: '아랍에미리트', region: '아시아·중동', lat: 24.9, lon: 55.16 },
  { code: 'SHJ', en: 'Sharjah', city: '샤르자', country: '아랍에미리트', region: '아시아·중동', lat: 25.33, lon: 55.52 },
  { code: 'KHI', en: 'Karachi', city: '카라치', country: '파키스탄', region: '아시아·중동', lat: 24.91, lon: 67.16 },
  { code: 'LHE', en: 'Lahore', city: '라호르', country: '파키스탄', region: '아시아·중동', lat: 31.52, lon: 74.4 },
  { code: 'BGW', en: 'Baghdad', city: '바그다드', country: '이라크', region: '아시아·중동', lat: 33.26, lon: 44.23 },
  { code: 'DAM', en: 'Damascus', city: '다마스쿠스', country: '시리아', region: '아시아·중동', lat: 33.41, lon: 36.52 },
  { code: 'FAI', en: 'Fairbanks', city: '페어뱅크스', country: '미국', region: '아메리카', lat: 64.82, lon: -147.86 },
  { code: 'DVO', en: 'Davao', city: '다바오', country: '필리핀', region: '동남아시아', lat: 7.13, lon: 125.65 },
  { code: 'AEP', en: 'Buenos Aires Aeroparque', city: '부에노스아이레스 아에로파르케', country: '아르헨티나', region: '아메리카', lat: -34.56, lon: -58.42 },
  { code: 'BEL', en: 'Belem', city: '벨렝', country: '브라질', region: '아메리카', lat: -1.38, lon: -48.48 },
  { code: 'BSB', en: 'Brasilia', city: '브라질리아', country: '브라질', region: '아메리카', lat: -15.87, lon: -47.92 },
  { code: 'CNF', en: 'Belo Horizonte', city: '벨루오리존치', country: '브라질', region: '아메리카', lat: -19.64, lon: -43.97 },
  { code: 'MAO', en: 'Manaus', city: '마나우스', country: '브라질', region: '아메리카', lat: -3.04, lon: -60.05 },
  { code: 'FLN', en: 'Florianopolis', city: '플로리아노폴리스', country: '브라질', region: '아메리카', lat: -27.67, lon: -48.55 },
  { code: 'SSA', en: 'Salvador', city: '사우바도르', country: '브라질', region: '아메리카', lat: -12.91, lon: -38.32 },
  { code: 'GYE', en: 'Guayaquil', city: '과야킬', country: '에콰도르', region: '아메리카', lat: -2.16, lon: -79.88 },
  { code: 'ASU', en: 'Asuncion', city: '아순시온', country: '파라과이', region: '아메리카', lat: -25.24, lon: -57.51 },
  { code: 'AGT', en: 'Ciudad del Este', city: '시우다드델에스테', country: '파라과이', region: '아메리카', lat: -25.46, lon: -54.84 },
  { code: 'VVI', en: 'Santa Cruz', city: '산타크루스(볼리비아)', country: '볼리비아', region: '아메리카', lat: -17.64, lon: -63.14 },
  { code: 'PBM', en: 'Paramaribo', city: '파라마리보', country: '수리남', region: '아메리카', lat: 5.45, lon: -55.19 },
  { code: 'CAY', en: 'Cayenne', city: '카옌', country: '프랑스령 기아나', region: '아메리카', lat: 4.82, lon: -52.36 },
  { code: 'CUZ', en: 'Cusco', city: '쿠스코', country: '페루', region: '아메리카', lat: -13.54, lon: -71.94 },
  { code: 'MVD', en: 'Montevideo', city: '몬테비데오', country: '우루과이', region: '아메리카', lat: -34.84, lon: -56.03 },
  { code: 'BLA', en: 'Barcelona Venezuela', city: '바르셀로나(베네수엘라)', country: '베네수엘라', region: '아메리카', lat: 10.11, lon: -64.69 },
  { code: 'CCS', en: 'Caracas', city: '카라카스', country: '베네수엘라', region: '아메리카', lat: 10.6, lon: -66.99 },
  { code: 'FDF', en: 'Fort-de-France', city: '포르드프랑스', country: '마르티니크', region: '아메리카', lat: 14.59, lon: -61 },
  { code: 'PTP', en: 'Pointe-a-Pitre', city: '푸앵타피트르', country: '과들루프', region: '아메리카', lat: 16.27, lon: -61.53 },
  { code: 'UVF', en: 'Saint Lucia', city: '세인트루시아', country: '세인트루시아', region: '아메리카', lat: 13.73, lon: -60.95 },
  { code: 'AUA', en: 'Aruba', city: '아루바', country: '아루바', region: '아메리카', lat: 12.5, lon: -70.02 },
  { code: 'BON', en: 'Bonaire', city: '보네르', country: '네덜란드령 카리브', region: '아메리카', lat: 12.13, lon: -68.27 },
  { code: 'CUR', en: 'Curacao', city: '퀴라소', country: '퀴라소', region: '아메리카', lat: 12.19, lon: -68.96 },
  { code: 'SXM', en: 'Sint Maarten', city: '신트마르턴', country: '신트마르턴', region: '아메리카', lat: 18.04, lon: -63.11 },
  { code: 'FRU', en: 'Bishkek', city: '비슈케크', country: '키르기스스탄', region: '아시아·중동', lat: 43.06, lon: 74.48 },
  { code: 'HSA', en: 'Turkistan', city: '투르키스탄', country: '카자흐스탄', region: '아시아·중동', lat: 43.31, lon: 68.55 },
  { code: 'GYD', en: 'Baku', city: '바쿠', country: '아제르바이잔', region: '아시아·중동', lat: 40.47, lon: 50.05 },
  { code: 'EVN', en: 'Yerevan', city: '예레반', country: '아르메니아', region: '아시아·중동', lat: 40.15, lon: 44.4 },
  { code: 'TBS', en: 'Tbilisi', city: '트빌리시', country: '조지아', region: '아시아·중동', lat: 41.67, lon: 44.95 },
  { code: 'KBP', en: 'Kyiv', city: '키이우', country: '우크라이나', region: '유럽·아프리카', lat: 50.35, lon: 30.89 },
  { code: 'LWO', en: 'Lviv', city: '리비우', country: '우크라이나', region: '유럽·아프리카', lat: 49.81, lon: 23.96 },
  { code: 'LED', en: 'Saint Petersburg', city: '상트페테르부르크', country: '러시아', region: '유럽·아프리카', lat: 59.8, lon: 30.26 },
  { code: 'MSQ', en: 'Minsk', city: '민스크', country: '벨라루스', region: '유럽·아프리카', lat: 53.89, lon: 28.04 },
  { code: 'KJA', en: 'Krasnoyarsk', city: '크라스노야르스크', country: '러시아', region: '유럽·아프리카', lat: 56.17, lon: 92.49 },
  { code: 'ROV', en: 'Rostov-on-Don', city: '로스토프나도누', country: '러시아', region: '유럽·아프리카', lat: 47.49, lon: 39.92 },
  { code: 'AER', en: 'Sochi', city: '소치', country: '러시아', region: '유럽·아프리카', lat: 43.45, lon: 39.96 },
  { code: 'SVX', en: 'Yekaterinburg', city: '예카테린부르크', country: '러시아', region: '아시아·중동', lat: 56.74, lon: 60.8 },
  { code: 'ASB', en: 'Ashgabat', city: '아시가바트', country: '투르크메니스탄', region: '아시아·중동', lat: 37.99, lon: 58.36 },
  { code: 'ZIA', en: 'Moscow Zhukovsky', city: '모스크바 주콥스키', country: '러시아', region: '유럽·아프리카', lat: 55.55, lon: 38.15 },
  { code: 'DME', en: 'Moscow Domodedovo', city: '모스크바 도모데도보', country: '러시아', region: '유럽·아프리카', lat: 55.41, lon: 37.91 },
  { code: 'SVO', en: 'Moscow Sheremetyevo', city: '모스크바 셰레메티예보', country: '러시아', region: '유럽·아프리카', lat: 55.97, lon: 37.41 },
  { code: 'VKO', en: 'Moscow Vnukovo', city: '모스크바 브누코보', country: '러시아', region: '유럽·아프리카', lat: 55.59, lon: 37.26 },
  { code: 'KZN', en: 'Kazan', city: '카잔', country: '러시아', region: '유럽·아프리카', lat: 55.61, lon: 49.28 },
  { code: 'GSV', en: 'Saratov', city: '사라토프', country: '러시아', region: '유럽·아프리카', lat: 51.71, lon: 46.17 },
  { code: 'UFA', en: 'Ufa', city: '우파', country: '러시아', region: '유럽·아프리카', lat: 54.56, lon: 55.87 },
  { code: 'KUF', en: 'Samara', city: '사마라', country: '러시아', region: '유럽·아프리카', lat: 53.5, lon: 50.16 },
  { code: 'GOI', en: 'Goa', city: '고아', country: '인도', region: '아시아·중동', lat: 15.38, lon: 73.83 },
  { code: 'HRI', en: 'Hambantota', city: '함반토타', country: '스리랑카', region: '아시아·중동', lat: 6.28, lon: 81.12 },
  { code: 'COK', en: 'Kochi', city: '코치(인도)', country: '인도', region: '아시아·중동', lat: 10.15, lon: 76.4 },
  { code: 'HYD', en: 'Hyderabad', city: '하이데라바드', country: '인도', region: '아시아·중동', lat: 17.23, lon: 78.43 },
  { code: 'TRV', en: 'Thiruvananthapuram', city: '티루바난타푸람', country: '인도', region: '아시아·중동', lat: 8.48, lon: 76.92 },
  { code: 'MDL', en: 'Mandalay', city: '만달레이', country: '미얀마', region: '동남아시아', lat: 21.7, lon: 95.98 },
  { code: 'UPG', en: 'Makassar', city: '마카사르', country: '인도네시아', region: '동남아시아', lat: -5.06, lon: 119.55 },
  { code: 'DJJ', en: 'Jayapura', city: '자야푸라', country: '인도네시아', region: '동남아시아', lat: -2.58, lon: 140.52 },
  { code: 'BPN', en: 'Balikpapan', city: '발릭파판', country: '인도네시아', region: '동남아시아', lat: -1.27, lon: 116.89 },
  { code: 'KNO', en: 'Medan', city: '메단', country: '인도네시아', region: '동남아시아', lat: 3.64, lon: 98.87 },
  { code: 'HET', en: 'Hohhot', city: '후허하오터', country: '중국', region: '중화권', lat: 40.85, lon: 111.82 },
  { code: 'TYN', en: 'Taiyuan', city: '타이위안', country: '중국', region: '중화권', lat: 37.75, lon: 112.63 },
  { code: 'NNG', en: 'Nanning', city: '난닝', country: '중국', region: '중화권', lat: 22.61, lon: 108.17 },
  { code: 'LHW', en: 'Lanzhou', city: '란저우', country: '중국', region: '중화권', lat: 36.52, lon: 103.62 },
  { code: 'KHN', en: 'Nanchang', city: '난창', country: '중국', region: '중화권', lat: 28.86, lon: 115.9 },
  { code: 'WNZ', en: 'Wenzhou', city: '원저우', country: '중국', region: '중화권', lat: 27.91, lon: 120.85 },
  { code: 'KWE', en: 'Guiyang', city: '구이양', country: '중국', region: '중화권', lat: 26.54, lon: 106.8 },
  { code: 'AXF', en: 'Alxa', city: '알라산 바얀하오터', country: '중국', region: '중화권', lat: 38.75, lon: 105.59 },
  { code: 'ZQZ', en: 'Zhangjiakou', city: '장자커우', country: '중국', region: '중화권', lat: 40.74, lon: 114.93 },
  { code: 'XAI', en: 'Xinyang', city: '신양', country: '중국', region: '중화권', lat: 32.54, lon: 114.08 },
  { code: 'HUZ', en: 'Huizhou', city: '후이저우', country: '중국', region: '중화권', lat: 23.05, lon: 114.6 },
  { code: 'HSC', en: 'Shaoguan', city: '사오관', country: '중국', region: '중화권', lat: 24.98, lon: 113.42 },
  { code: 'JGS', en: 'Jinggangshan', city: '징강산', country: '중국', region: '중화권', lat: 26.86, lon: 114.74 },
  { code: 'LYG', en: 'Lianyungang', city: '롄윈강', country: '중국', region: '중화권', lat: 34.41, lon: 119.18 },
  { code: 'THQ', en: 'Tianshui', city: '톈수이', country: '중국', region: '중화권', lat: 34.56, lon: 105.86 },
  { code: 'NTG', en: 'Nantong', city: '난퉁', country: '중국', region: '중화권', lat: 32.07, lon: 120.98 },
  { code: 'DBC', en: 'Baicheng', city: '바이청', country: '중국', region: '중화권', lat: 45.51, lon: 123.02 },
  { code: 'ENY', en: 'Yan\'an', city: '옌안', country: '중국', region: '중화권', lat: 36.48, lon: 109.46 },
  { code: 'HIA', en: 'Huai\'an', city: '화이안', country: '중국', region: '중화권', lat: 33.79, lon: 119.13 },
  { code: 'JGD', en: 'Jiagedaqi', city: '자거다치', country: '중국', region: '중화권', lat: 50.37, lon: 124.12 },
  { code: 'JIQ', en: 'Qianjiang', city: '첸장', country: '중국', region: '중화권', lat: 29.51, lon: 108.83 },
  { code: 'JNZ', en: 'Jinzhou', city: '진저우', country: '중국', region: '중화권', lat: 40.94, lon: 121.28 },
  { code: 'LZG', en: 'Langzhong', city: '랑중', country: '중국', region: '중화권', lat: 31.5, lon: 106.03 },
  { code: 'NBS', en: 'Changbaishan', city: '창바이산(백두산)', country: '중국', region: '중화권', lat: 42.07, lon: 127.6 },
  { code: 'KNH', en: 'Kinmen', city: '진먼', country: '대만', region: '중화권', lat: 24.43, lon: 118.36 },
  { code: 'LZN', en: 'Matsu Nangan', city: '마쭈 난간', country: '대만', region: '중화권', lat: 26.16, lon: 119.96 },
  { code: 'TTT', en: 'Taitung', city: '타이둥', country: '대만', region: '중화권', lat: 22.75, lon: 121.1 },
  { code: 'CYI', en: 'Chiayi', city: '자이', country: '대만', region: '중화권', lat: 23.46, lon: 120.39 },
  { code: 'HCN', en: 'Hengchun', city: '헝춘', country: '대만', region: '중화권', lat: 22.04, lon: 120.73 },
  { code: 'KYD', en: 'Lanyu', city: '란위', country: '대만', region: '중화권', lat: 22.03, lon: 121.54 },
  { code: 'MFK', en: 'Matsu Beigan', city: '마쭈 베이간', country: '대만', region: '중화권', lat: 26.22, lon: 120 },
  { code: 'TNN', en: 'Tainan', city: '타이난', country: '대만', region: '중화권', lat: 22.95, lon: 120.21 },
  { code: 'MZG', en: 'Penghu', city: '펑후', country: '대만', region: '중화권', lat: 23.57, lon: 119.63 },
  { code: 'PIF', en: 'Pingtung', city: '핑둥', country: '대만', region: '중화권', lat: 22.7, lon: 120.48 },
  { code: 'HUN', en: 'Hualien', city: '화롄', country: '대만', region: '중화권', lat: 24.02, lon: 121.62 },
  { code: 'MMJ', en: 'Matsumoto', city: '마쓰모토', country: '일본', region: '일본', lat: 36.17, lon: 137.92 },
  { code: 'IBR', en: 'Ibaraki', city: '이바라키', country: '일본', region: '일본', lat: 36.18, lon: 140.41 },
  { code: 'SHM', en: 'Nanki Shirahama', city: '난키시라하마', country: '일본', region: '일본', lat: 33.66, lon: 135.36 },
  { code: 'OBO', en: 'Obihiro', city: '오비히로', country: '일본', region: '일본', lat: 42.73, lon: 143.22 },
  { code: 'KUH', en: 'Kushiro', city: '구시로', country: '일본', region: '일본', lat: 43.04, lon: 144.19 },
  { code: 'MMB', en: 'Memanbetsu', city: '메만베쓰', country: '일본', region: '일본', lat: 43.88, lon: 144.16 },
  { code: 'SHB', en: 'Nakashibetsu', city: '나카시베쓰', country: '일본', region: '일본', lat: 43.58, lon: 144.96 },
  { code: 'OKD', en: 'Sapporo Okadama', city: '삿포로 오카다마', country: '일본', region: '일본', lat: 43.12, lon: 141.38 },
  { code: 'WKJ', en: 'Wakkanai', city: '왓카나이', country: '일본', region: '일본', lat: 45.4, lon: 141.8 },
  { code: 'MBE', en: 'Monbetsu', city: '몬베쓰', country: '일본', region: '일본', lat: 44.3, lon: 143.4 },
  { code: 'OIR', en: 'Okushiri', city: '오쿠시리', country: '일본', region: '일본', lat: 42.07, lon: 139.43 },
  { code: 'RIS', en: 'Rishiri', city: '리시리', country: '일본', region: '일본', lat: 45.24, lon: 141.19 },
  { code: 'KUM', en: 'Yakushima', city: '야쿠시마', country: '일본', region: '일본', lat: 30.39, lon: 130.66 },
  { code: 'TNE', en: 'Tanegashima', city: '다네가시마', country: '일본', region: '일본', lat: 30.61, lon: 130.99 },
  { code: 'ASJ', en: 'Amami', city: '아마미', country: '일본', region: '일본', lat: 28.43, lon: 129.71 },
  { code: 'OKE', en: 'Okinoerabu', city: '오키노에라부', country: '일본', region: '일본', lat: 27.43, lon: 128.7 },
  { code: 'KKX', en: 'Kikai', city: '기카이', country: '일본', region: '일본', lat: 28.32, lon: 129.93 },
  { code: 'TKN', en: 'Tokunoshima', city: '도쿠노시마', country: '일본', region: '일본', lat: 27.84, lon: 128.88 },
  { code: 'NKM', en: 'Nagoya Komaki', city: '나고야 고마키', country: '일본', region: '일본', lat: 35.26, lon: 136.92 },
  { code: 'OKI', en: 'Oki', city: '오키', country: '일본', region: '일본', lat: 36.18, lon: 133.32 },
  { code: 'NTQ', en: 'Noto', city: '노토', country: '일본', region: '일본', lat: 37.29, lon: 136.96 },
  { code: 'IWK', en: 'Iwakuni', city: '이와쿠니', country: '일본', region: '일본', lat: 34.15, lon: 132.25 },
  { code: 'TTJ', en: 'Tottori', city: '돗토리', country: '일본', region: '일본', lat: 35.53, lon: 134.17 },
  { code: 'IWJ', en: 'Iwami', city: '이와미', country: '일본', region: '일본', lat: 34.68, lon: 131.79 },
  { code: 'GAJ', en: 'Yamagata', city: '야마가타', country: '일본', region: '일본', lat: 38.41, lon: 140.37 },
  { code: 'SDS', en: 'Sado', city: '사도', country: '일본', region: '일본', lat: 38.06, lon: 138.41 },
  { code: 'FKS', en: 'Fukushima', city: '후쿠시마', country: '일본', region: '일본', lat: 37.23, lon: 140.43 },
  { code: 'HNA', en: 'Hanamaki', city: '하나마키', country: '일본', region: '일본', lat: 39.43, lon: 141.13 },
  { code: 'MSJ', en: 'Misawa', city: '미사와', country: '일본', region: '일본', lat: 40.7, lon: 141.37 },
  { code: 'ONJ', en: 'Odate Noshiro', city: '오다테노시로', country: '일본', region: '일본', lat: 40.19, lon: 140.37 },
  { code: 'SYO', en: 'Shonai', city: '쇼나이', country: '일본', region: '일본', lat: 38.81, lon: 139.79 },
  { code: 'HAC', en: 'Hachijojima', city: '하치조지마', country: '일본', region: '일본', lat: 33.12, lon: 139.79 },
  { code: 'OIM', en: 'Izu Oshima', city: '이즈오시마', country: '일본', region: '일본', lat: 34.78, lon: 139.36 },
  { code: 'MYE', en: 'Miyakejima', city: '미야케지마', country: '일본', region: '일본', lat: 34.07, lon: 139.56 },
  { code: 'UEO', en: 'Kumejima', city: '구메지마', country: '일본', region: '일본', lat: 26.36, lon: 126.71 },
  { code: 'MMD', en: 'Minamidaito', city: '미나미다이토', country: '일본', region: '일본', lat: 25.85, lon: 131.26 },
  { code: 'KTD', en: 'Kitadaito', city: '기타다이토', country: '일본', region: '일본', lat: 25.94, lon: 131.33 },
  { code: 'TRA', en: 'Tarama', city: '다라마', country: '일본', region: '일본', lat: 24.65, lon: 124.68 },
  { code: 'RNJ', en: 'Yoron', city: '요론', country: '일본', region: '일본', lat: 27.04, lon: 128.4 },
  { code: 'OGN', en: 'Yonaguni', city: '요나구니', country: '일본', region: '일본', lat: 24.47, lon: 122.98 },
  { code: 'BSO', en: 'Basco', city: '바스코', country: '필리핀', region: '동남아시아', lat: 20.45, lon: 121.98 },
  { code: 'SQD', en: 'Shangrao', city: '상라오', country: '중국', region: '중화권', lat: 28.38, lon: 117.96 },
  { code: 'SQJ', en: 'Sanming', city: '싼밍', country: '중국', region: '중화권', lat: 26.43, lon: 117.83 },
  { code: 'BQS', en: 'Blagoveshchensk', city: '블라고베셴스크', country: '러시아', region: '아시아·중동', lat: 50.43, lon: 127.41 },
  { code: 'KXK', en: 'Komsomolsk-on-Amur', city: '콤소몰스크나아무레', country: '러시아', region: '아시아·중동', lat: 50.41, lon: 136.93 },
  { code: 'HTA', en: 'Chita', city: '치타', country: '러시아', region: '유럽·아프리카', lat: 52.03, lon: 113.31 },
  { code: 'YYA', en: 'Yueyang', city: '웨양', country: '중국', region: '중화권', lat: 29.31, lon: 113.28 },
  { code: 'CDE', en: 'Chengde', city: '청더', country: '중국', region: '중화권', lat: 41.12, lon: 118.07 },
  { code: 'CIF', en: 'Chifeng', city: '츠펑', country: '중국', region: '중화권', lat: 42.16, lon: 118.84 },
  { code: 'BPE', en: 'Qinhuangdao', city: '친황다오', country: '중국', region: '중화권', lat: 39.67, lon: 119.06 },
  { code: 'DSN', en: 'Ordos', city: '오르도스', country: '중국', region: '중화권', lat: 39.49, lon: 109.86 },
  { code: 'ERL', en: 'Erenhot', city: '얼롄하오터', country: '중국', region: '중화권', lat: 43.42, lon: 112.1 },
  { code: 'YIE', en: 'Arxan', city: '아얼산', country: '중국', region: '중화권', lat: 47.31, lon: 119.91 },
  { code: 'HDG', en: 'Handan', city: '한단', country: '중국', region: '중화권', lat: 36.53, lon: 114.43 },
  { code: 'HUO', en: 'Holingol', city: '훠린궈러', country: '중국', region: '중화권', lat: 45.49, lon: 119.41 },
  { code: 'HLD', en: 'Hailar', city: '하이라얼', country: '중국', region: '중화권', lat: 49.21, lon: 119.82 },
  { code: 'LFQ', en: 'Linfen', city: '린펀', country: '중국', region: '중화권', lat: 36.13, lon: 111.64 },
  { code: 'LLV', en: 'Lvliang', city: '뤼량', country: '중국', region: '중화권', lat: 37.68, lon: 111.14 },
  { code: 'NZH', en: 'Manzhouli', city: '만저우리', country: '중국', region: '중화권', lat: 49.57, lon: 117.33 },
  { code: 'BAV', en: 'Baotou', city: '바오터우', country: '중국', region: '중화권', lat: 40.56, lon: 110 },
  { code: 'TGO', en: 'Tongliao', city: '퉁랴오', country: '중국', region: '중화권', lat: 43.56, lon: 122.2 },
  { code: 'UCB', en: 'Ulanqab', city: '울란차브', country: '중국', region: '중화권', lat: 41.13, lon: 113.11 },
  { code: 'XIL', en: 'Xilinhot', city: '시린하오터', country: '중국', region: '중화권', lat: 43.92, lon: 115.96 },
  { code: 'RLK', en: 'Bayannur', city: '바옌나오얼', country: '중국', region: '중화권', lat: 40.93, lon: 107.74 },
  { code: 'NZL', en: 'Zhalantun', city: '자란툰', country: '중국', region: '중화권', lat: 47.87, lon: 122.77 },
  { code: 'CGD', en: 'Changde', city: '창더', country: '중국', region: '중화권', lat: 28.92, lon: 111.64 },
  { code: 'HJJ', en: 'Huaihua', city: '화이화', country: '중국', region: '중화권', lat: 27.44, lon: 109.7 },
  { code: 'HCZ', en: 'Chenzhou', city: '천저우', country: '중국', region: '중화권', lat: 25.75, lon: 112.85 },
  { code: 'LLF', en: 'Yongzhou', city: '융저우', country: '중국', region: '중화권', lat: 26.34, lon: 111.61 },
  { code: 'SWA', en: 'Jieyang Chaoshan', city: '제양·차오산', country: '중국', region: '중화권', lat: 23.55, lon: 116.5 },
  { code: 'WGN', en: 'Shaoyang', city: '사오양', country: '중국', region: '중화권', lat: 26.81, lon: 110.64 },
  { code: 'ENH', en: 'Enshi', city: '언스', country: '중국', region: '중화권', lat: 30.32, lon: 109.49 },
  { code: 'SHS', en: 'Jingzhou', city: '징저우', country: '중국', region: '중화권', lat: 30.29, lon: 112.45 },
  { code: 'LYA', en: 'Luoyang', city: '뤄양', country: '중국', region: '중화권', lat: 34.74, lon: 112.39 },
  { code: 'HPG', en: 'Shennongjia', city: '선눙자', country: '중국', region: '중화권', lat: 31.63, lon: 110.34 },
  { code: 'WDS', en: 'Shiyan', city: '스옌', country: '중국', region: '중화권', lat: 32.59, lon: 110.91 },
  { code: 'XFN', en: 'Xiangyang', city: '샹양', country: '중국', region: '중화권', lat: 32.15, lon: 112.29 },
  { code: 'YIH', en: 'Yichang', city: '이창', country: '중국', region: '중화권', lat: 30.55, lon: 111.48 },
  { code: 'INC', en: 'Yinchuan', city: '인촨', country: '중국', region: '중화권', lat: 38.32, lon: 106.39 },
  { code: 'JNG', en: 'Jining', city: '지닝', country: '중국', region: '중화권', lat: 35.29, lon: 116.35 },
  { code: 'LNL', en: 'Longnan', city: '룽난', country: '중국', region: '중화권', lat: 33.79, lon: 105.79 },
  { code: 'IQN', en: 'Qingyang', city: '칭양', country: '중국', region: '중화권', lat: 35.8, lon: 107.6 },
  { code: 'ZHY', en: 'Zhongwei', city: '중웨이', country: '중국', region: '중화권', lat: 37.57, lon: 105.15 },
  { code: 'DLZ', en: 'Dalanzadgad', city: '달란자드가드', country: '몽골', region: '아시아·중동', lat: 43.61, lon: 104.37 },
  { code: 'AQG', en: 'Anqing', city: '안칭', country: '중국', region: '중화권', lat: 30.58, lon: 117.05 },
  { code: 'CZX', en: 'Changzhou', city: '창저우', country: '중국', region: '중화권', lat: 31.92, lon: 119.78 },
  { code: 'FUG', en: 'Fuyang', city: '푸양', country: '중국', region: '중화권', lat: 32.88, lon: 115.73 },
  { code: 'HZA', en: 'Heze', city: '허쩌', country: '중국', region: '중화권', lat: 35.21, lon: 115.74 },
  { code: 'JDZ', en: 'Jingdezhen', city: '징더전', country: '중국', region: '중화권', lat: 29.34, lon: 117.18 },
  { code: 'JUZ', en: 'Quzhou', city: '취저우', country: '중국', region: '중화권', lat: 28.97, lon: 118.9 },
  { code: 'LCX', en: 'Longyan', city: '룽옌', country: '중국', region: '중화권', lat: 25.67, lon: 116.75 },
  { code: 'HYN', en: 'Taizhou', city: '타이저우', country: '중국', region: '중화권', lat: 28.56, lon: 121.43 },
  { code: 'HFE', en: 'Hefei', city: '허페이', country: '중국', region: '중화권', lat: 31.99, lon: 116.98 },
  { code: 'JJN', en: 'Quanzhou', city: '취안저우', country: '중국', region: '중화권', lat: 24.8, lon: 118.59 },
  { code: 'RIZ', en: 'Rizhao', city: '르자오', country: '중국', region: '중화권', lat: 35.41, lon: 119.32 },
  { code: 'TXN', en: 'Huangshan', city: '황산', country: '중국', region: '중화권', lat: 29.73, lon: 118.26 },
  { code: 'WEF', en: 'Weifang', city: '웨이팡', country: '중국', region: '중화권', lat: 36.65, lon: 119.12 },
  { code: 'WUS', en: 'Wuyishan', city: '우이산', country: '중국', region: '중화권', lat: 27.7, lon: 118 },
  { code: 'XUZ', en: 'Xuzhou', city: '쉬저우', country: '중국', region: '중화권', lat: 34.06, lon: 117.56 },
  { code: 'YTY', en: 'Yangzhou', city: '양저우', country: '중국', region: '중화권', lat: 32.56, lon: 119.72 },
  { code: 'YIC', en: 'Yichun Jiangxi', city: '이춘(장시)', country: '중국', region: '중화권', lat: 27.8, lon: 114.31 },
  { code: 'YNZ', en: 'Yancheng', city: '옌청', country: '중국', region: '중화권', lat: 33.43, lon: 120.2 },
  { code: 'YIW', en: 'Yiwu', city: '이우', country: '중국', region: '중화권', lat: 29.34, lon: 120.03 },
  { code: 'GYS', en: 'Guangyuan', city: '광위안', country: '중국', region: '중화권', lat: 32.39, lon: 105.69 },
  { code: 'TEN', en: 'Tongren', city: '퉁런', country: '중국', region: '중화권', lat: 27.88, lon: 109.31 },
  { code: 'CQW', en: 'Chongqing Wulong', city: '충칭 우룽', country: '중국', region: '중화권', lat: 29.47, lon: 107.69 },
  { code: 'AOG', en: 'Anshan', city: '안산', country: '중국', region: '중화권', lat: 41.11, lon: 122.85 },
  { code: 'CNI', en: 'Changhai', city: '창하이', country: '중국', region: '중화권', lat: 39.27, lon: 122.67 },
  { code: 'CHG', en: 'Chaoyang', city: '차오양', country: '중국', region: '중화권', lat: 41.54, lon: 120.43 },
  { code: 'DTU', en: 'Wudalianchi', city: '우다롄츠', country: '중국', region: '중화권', lat: 48.44, lon: 126.13 },
  { code: 'FYJ', en: 'Fuyuan', city: '푸위안', country: '중국', region: '중화권', lat: 48.2, lon: 134.36 },
  { code: 'HEK', en: 'Heihe', city: '헤이허', country: '중국', region: '중화권', lat: 50.17, lon: 127.31 },
  { code: 'JMU', en: 'Jiamusi', city: '자무쓰', country: '중국', region: '중화권', lat: 46.84, lon: 130.46 },
  { code: 'JSJ', en: 'Jiansanjiang', city: '젠싼장', country: '중국', region: '중화권', lat: 47.11, lon: 132.66 },
  { code: 'JXA', en: 'Jixi', city: '지시', country: '중국', region: '중화권', lat: 45.29, lon: 131.19 },
  { code: 'LDS', en: 'Yichun Heilongjiang', city: '이춘(헤이룽장)', country: '중국', region: '중화권', lat: 47.75, lon: 129.02 },
  { code: 'OHE', en: 'Mohe', city: '모허', country: '중국', region: '중화권', lat: 52.92, lon: 122.42 },
  { code: 'NDG', en: 'Qiqihar', city: '치치하얼', country: '중국', region: '중화권', lat: 47.24, lon: 123.92 },
  { code: 'YSQ', en: 'Songyuan', city: '쑹위안', country: '중국', region: '중화권', lat: 44.94, lon: 124.55 },
  { code: 'TNH', en: 'Tonghua', city: '퉁화', country: '중국', region: '중화권', lat: 42.25, lon: 125.7 },
  { code: 'YKH', en: 'Yingkou', city: '잉커우', country: '중국', region: '중화권', lat: 40.54, lon: 122.36 },
];
