/* 포커스 에어 공항 목록 — code: IATA 코드, lat/lon: 위도·경도(도) */
window.AIRPORTS = [
  // 한국
  { code: 'ICN', city: '인천', country: '대한민국', region: '한국', lat: 37.46, lon: 126.44 },
  { code: 'GMP', city: '서울 김포', country: '대한민국', region: '한국', lat: 37.56, lon: 126.80 },
  { code: 'PUS', city: '부산 김해', country: '대한민국', region: '한국', lat: 35.18, lon: 128.94 },
  { code: 'CJU', city: '제주', country: '대한민국', region: '한국', lat: 33.51, lon: 126.49 },
  { code: 'CJJ', city: '청주', country: '대한민국', region: '한국', lat: 36.72, lon: 127.50 },
  { code: 'TAE', city: '대구', country: '대한민국', region: '한국', lat: 35.89, lon: 128.66 },
  { code: 'KWJ', city: '광주', country: '대한민국', region: '한국', lat: 35.13, lon: 126.81 },
  { code: 'RSU', city: '여수', country: '대한민국', region: '한국', lat: 34.84, lon: 127.62 },
  { code: 'USN', city: '울산', country: '대한민국', region: '한국', lat: 35.59, lon: 129.35 },
  { code: 'YNY', city: '양양', country: '대한민국', region: '한국', lat: 38.06, lon: 128.67 },
  // 일본
  { code: 'NRT', city: '도쿄 나리타', country: '일본', region: '일본', lat: 35.77, lon: 140.39 },
  { code: 'HND', city: '도쿄 하네다', country: '일본', region: '일본', lat: 35.55, lon: 139.78 },
  { code: 'KIX', city: '오사카 간사이', country: '일본', region: '일본', lat: 34.43, lon: 135.23 },
  { code: 'FUK', city: '후쿠오카', country: '일본', region: '일본', lat: 33.59, lon: 130.45 },
  { code: 'CTS', city: '삿포로', country: '일본', region: '일본', lat: 42.78, lon: 141.69 },
  { code: 'OKA', city: '오키나와', country: '일본', region: '일본', lat: 26.20, lon: 127.65 },
  // 중화권
  { code: 'PEK', city: '베이징', country: '중국', region: '중화권', lat: 40.08, lon: 116.58 },
  { code: 'PVG', city: '상하이', country: '중국', region: '중화권', lat: 31.14, lon: 121.81 },
  { code: 'HKG', city: '홍콩', country: '홍콩', region: '중화권', lat: 22.31, lon: 113.91 },
  { code: 'TPE', city: '타이베이', country: '대만', region: '중화권', lat: 25.08, lon: 121.23 },
  // 동남아시아
  { code: 'BKK', city: '방콕', country: '태국', region: '동남아시아', lat: 13.69, lon: 100.75 },
  { code: 'HAN', city: '하노이', country: '베트남', region: '동남아시아', lat: 21.22, lon: 105.81 },
  { code: 'DAD', city: '다낭', country: '베트남', region: '동남아시아', lat: 16.04, lon: 108.20 },
  { code: 'SGN', city: '호찌민', country: '베트남', region: '동남아시아', lat: 10.82, lon: 106.66 },
  { code: 'MNL', city: '마닐라', country: '필리핀', region: '동남아시아', lat: 14.51, lon: 121.02 },
  { code: 'CEB', city: '세부', country: '필리핀', region: '동남아시아', lat: 10.31, lon: 123.98 },
  { code: 'SIN', city: '싱가포르', country: '싱가포르', region: '동남아시아', lat: 1.36, lon: 103.99 },
  { code: 'KUL', city: '쿠알라룸푸르', country: '말레이시아', region: '동남아시아', lat: 2.75, lon: 101.71 },
  { code: 'DPS', city: '발리', country: '인도네시아', region: '동남아시아', lat: -8.75, lon: 115.17 },
  // 아시아 기타·중동
  { code: 'UBN', city: '울란바토르', country: '몽골', region: '아시아·중동', lat: 47.65, lon: 106.82 },
  { code: 'VVO', city: '블라디보스토크', country: '러시아', region: '아시아·중동', lat: 43.40, lon: 132.15 },
  { code: 'DEL', city: '델리', country: '인도', region: '아시아·중동', lat: 28.56, lon: 77.10 },
  { code: 'DXB', city: '두바이', country: '아랍에미리트', region: '아시아·중동', lat: 25.25, lon: 55.36 },
  { code: 'IST', city: '이스탄불', country: '튀르키예', region: '아시아·중동', lat: 41.26, lon: 28.74 },
  // 오세아니아·태평양
  { code: 'GUM', city: '괌', country: '미국령 괌', region: '오세아니아·태평양', lat: 13.48, lon: 144.80 },
  { code: 'HNL', city: '호놀룰루', country: '미국', region: '오세아니아·태평양', lat: 21.32, lon: -157.92 },
  { code: 'SYD', city: '시드니', country: '호주', region: '오세아니아·태평양', lat: -33.95, lon: 151.18 },
  { code: 'AKL', city: '오클랜드', country: '뉴질랜드', region: '오세아니아·태평양', lat: -37.01, lon: 174.79 },
  // 아메리카
  { code: 'YVR', city: '밴쿠버', country: '캐나다', region: '아메리카', lat: 49.19, lon: -123.18 },
  { code: 'SEA', city: '시애틀', country: '미국', region: '아메리카', lat: 47.45, lon: -122.31 },
  { code: 'SFO', city: '샌프란시스코', country: '미국', region: '아메리카', lat: 37.62, lon: -122.38 },
  { code: 'LAX', city: '로스앤젤레스', country: '미국', region: '아메리카', lat: 33.94, lon: -118.41 },
  { code: 'JFK', city: '뉴욕', country: '미국', region: '아메리카', lat: 40.64, lon: -73.78 },
  { code: 'GRU', city: '상파울루', country: '브라질', region: '아메리카', lat: -23.43, lon: -46.47 },
  // 유럽·아프리카
  { code: 'LHR', city: '런던', country: '영국', region: '유럽·아프리카', lat: 51.47, lon: -0.45 },
  { code: 'CDG', city: '파리', country: '프랑스', region: '유럽·아프리카', lat: 49.01, lon: 2.55 },
  { code: 'AMS', city: '암스테르담', country: '네덜란드', region: '유럽·아프리카', lat: 52.31, lon: 4.76 },
  { code: 'FRA', city: '프랑크푸르트', country: '독일', region: '유럽·아프리카', lat: 50.03, lon: 8.56 },
  { code: 'ZRH', city: '취리히', country: '스위스', region: '유럽·아프리카', lat: 47.46, lon: 8.55 },
  { code: 'PRG', city: '프라하', country: '체코', region: '유럽·아프리카', lat: 50.10, lon: 14.26 },
  { code: 'FCO', city: '로마', country: '이탈리아', region: '유럽·아프리카', lat: 41.80, lon: 12.25 },
  { code: 'BCN', city: '바르셀로나', country: '스페인', region: '유럽·아프리카', lat: 41.30, lon: 2.08 },
  { code: 'HEL', city: '헬싱키', country: '핀란드', region: '유럽·아프리카', lat: 60.32, lon: 24.96 },
  { code: 'CAI', city: '카이로', country: '이집트', region: '유럽·아프리카', lat: 30.12, lon: 31.41 },
  { code: 'JNB', city: '요하네스버그', country: '남아프리카공화국', region: '유럽·아프리카', lat: -26.14, lon: 28.24 },
];
