/* 포커스 에어 공항 목록 (248곳) — code: IATA 코드, en: 영어 방송용 이름, lat/lon: 위도·경도(도) */
window.AIRPORTS = [
  // 한국
  { code: 'ICN', en: 'Incheon', city: '인천', country: '대한민국', region: '한국', lat: 37.46, lon: 126.44 },
  { code: 'GMP', en: 'Seoul Gimpo', city: '서울 김포', country: '대한민국', region: '한국', lat: 37.56, lon: 126.80 },
  { code: 'PUS', en: 'Busan', city: '부산 김해', country: '대한민국', region: '한국', lat: 35.18, lon: 128.94 },
  { code: 'CJU', en: 'Jeju', city: '제주', country: '대한민국', region: '한국', lat: 33.51, lon: 126.49 },
  { code: 'CJJ', en: 'Cheongju', city: '청주', country: '대한민국', region: '한국', lat: 36.72, lon: 127.50 },
  { code: 'TAE', en: 'Daegu', city: '대구', country: '대한민국', region: '한국', lat: 35.89, lon: 128.66 },
  { code: 'KWJ', en: 'Gwangju', city: '광주', country: '대한민국', region: '한국', lat: 35.13, lon: 126.81 },
  { code: 'RSU', en: 'Yeosu', city: '여수', country: '대한민국', region: '한국', lat: 34.84, lon: 127.62 },
  { code: 'USN', en: 'Ulsan', city: '울산', country: '대한민국', region: '한국', lat: 35.59, lon: 129.35 },
  { code: 'YNY', en: 'Yangyang', city: '양양', country: '대한민국', region: '한국', lat: 38.06, lon: 128.67 },
  // 일본
  { code: 'NRT', en: 'Tokyo Narita', city: '도쿄 나리타', country: '일본', region: '일본', lat: 35.77, lon: 140.39 },
  { code: 'HND', en: 'Tokyo Haneda', city: '도쿄 하네다', country: '일본', region: '일본', lat: 35.55, lon: 139.78 },
  { code: 'KIX', en: 'Osaka Kansai', city: '오사카 간사이', country: '일본', region: '일본', lat: 34.43, lon: 135.23 },
  { code: 'FUK', en: 'Fukuoka', city: '후쿠오카', country: '일본', region: '일본', lat: 33.59, lon: 130.45 },
  { code: 'CTS', en: 'Sapporo', city: '삿포로', country: '일본', region: '일본', lat: 42.78, lon: 141.69 },
  { code: 'OKA', en: 'Okinawa', city: '오키나와', country: '일본', region: '일본', lat: 26.20, lon: 127.65 },
  // 중화권
  { code: 'PEK', en: 'Beijing', city: '베이징', country: '중국', region: '중화권', lat: 40.08, lon: 116.58 },
  { code: 'PVG', en: 'Shanghai', city: '상하이', country: '중국', region: '중화권', lat: 31.14, lon: 121.81 },
  { code: 'HKG', en: 'Hong Kong', city: '홍콩', country: '홍콩', region: '중화권', lat: 22.31, lon: 113.91 },
  { code: 'TPE', en: 'Taipei', city: '타이베이', country: '대만', region: '중화권', lat: 25.08, lon: 121.23 },
  // 동남아시아
  { code: 'BKK', en: 'Bangkok', city: '방콕', country: '태국', region: '동남아시아', lat: 13.69, lon: 100.75 },
  { code: 'HAN', en: 'Hanoi', city: '하노이', country: '베트남', region: '동남아시아', lat: 21.22, lon: 105.81 },
  { code: 'DAD', en: 'Da Nang', city: '다낭', country: '베트남', region: '동남아시아', lat: 16.04, lon: 108.20 },
  { code: 'SGN', en: 'Ho Chi Minh City', city: '호찌민', country: '베트남', region: '동남아시아', lat: 10.82, lon: 106.66 },
  { code: 'MNL', en: 'Manila', city: '마닐라', country: '필리핀', region: '동남아시아', lat: 14.51, lon: 121.02 },
  { code: 'CEB', en: 'Cebu', city: '세부', country: '필리핀', region: '동남아시아', lat: 10.31, lon: 123.98 },
  { code: 'SIN', en: 'Singapore', city: '싱가포르', country: '싱가포르', region: '동남아시아', lat: 1.36, lon: 103.99 },
  { code: 'KUL', en: 'Kuala Lumpur', city: '쿠알라룸푸르', country: '말레이시아', region: '동남아시아', lat: 2.75, lon: 101.71 },
  { code: 'DPS', en: 'Bali', city: '발리', country: '인도네시아', region: '동남아시아', lat: -8.75, lon: 115.17 },
  // 아시아 기타·중동
  { code: 'UBN', en: 'Ulaanbaatar', city: '울란바토르', country: '몽골', region: '아시아·중동', lat: 47.65, lon: 106.82 },
  { code: 'VVO', en: 'Vladivostok', city: '블라디보스토크', country: '러시아', region: '아시아·중동', lat: 43.40, lon: 132.15 },
  { code: 'DEL', en: 'Delhi', city: '델리', country: '인도', region: '아시아·중동', lat: 28.56, lon: 77.10 },
  { code: 'DXB', en: 'Dubai', city: '두바이', country: '아랍에미리트', region: '아시아·중동', lat: 25.25, lon: 55.36 },
  { code: 'IST', en: 'Istanbul', city: '이스탄불', country: '튀르키예', region: '아시아·중동', lat: 41.26, lon: 28.74 },
  // 오세아니아·태평양
  { code: 'GUM', en: 'Guam', city: '괌', country: '미국령 괌', region: '오세아니아·태평양', lat: 13.48, lon: 144.80 },
  { code: 'HNL', en: 'Honolulu', city: '호놀룰루', country: '미국', region: '오세아니아·태평양', lat: 21.32, lon: -157.92 },
  { code: 'SYD', en: 'Sydney', city: '시드니', country: '호주', region: '오세아니아·태평양', lat: -33.95, lon: 151.18 },
  { code: 'AKL', en: 'Auckland', city: '오클랜드', country: '뉴질랜드', region: '오세아니아·태평양', lat: -37.01, lon: 174.79 },
  // 아메리카
  { code: 'YVR', en: 'Vancouver', city: '밴쿠버', country: '캐나다', region: '아메리카', lat: 49.19, lon: -123.18 },
  { code: 'SEA', en: 'Seattle', city: '시애틀', country: '미국', region: '아메리카', lat: 47.45, lon: -122.31 },
  { code: 'SFO', en: 'San Francisco', city: '샌프란시스코', country: '미국', region: '아메리카', lat: 37.62, lon: -122.38 },
  { code: 'LAX', en: 'Los Angeles', city: '로스앤젤레스', country: '미국', region: '아메리카', lat: 33.94, lon: -118.41 },
  { code: 'JFK', en: 'New York', city: '뉴욕', country: '미국', region: '아메리카', lat: 40.64, lon: -73.78 },
  { code: 'GRU', en: 'Sao Paulo', city: '상파울루', country: '브라질', region: '아메리카', lat: -23.43, lon: -46.47 },
  // 유럽·아프리카
  { code: 'LHR', en: 'London', city: '런던', country: '영국', region: '유럽·아프리카', lat: 51.47, lon: -0.45 },
  { code: 'CDG', en: 'Paris', city: '파리', country: '프랑스', region: '유럽·아프리카', lat: 49.01, lon: 2.55 },
  { code: 'AMS', en: 'Amsterdam', city: '암스테르담', country: '네덜란드', region: '유럽·아프리카', lat: 52.31, lon: 4.76 },
  { code: 'FRA', en: 'Frankfurt', city: '프랑크푸르트', country: '독일', region: '유럽·아프리카', lat: 50.03, lon: 8.56 },
  { code: 'ZRH', en: 'Zurich', city: '취리히', country: '스위스', region: '유럽·아프리카', lat: 47.46, lon: 8.55 },
  { code: 'PRG', en: 'Prague', city: '프라하', country: '체코', region: '유럽·아프리카', lat: 50.10, lon: 14.26 },
  { code: 'FCO', en: 'Rome', city: '로마', country: '이탈리아', region: '유럽·아프리카', lat: 41.80, lon: 12.25 },
  { code: 'BCN', en: 'Barcelona', city: '바르셀로나', country: '스페인', region: '유럽·아프리카', lat: 41.30, lon: 2.08 },
  { code: 'HEL', en: 'Helsinki', city: '헬싱키', country: '핀란드', region: '유럽·아프리카', lat: 60.32, lon: 24.96 },
  { code: 'CAI', en: 'Cairo', city: '카이로', country: '이집트', region: '유럽·아프리카', lat: 30.12, lon: 31.41 },
  { code: 'JNB', en: 'Johannesburg', city: '요하네스버그', country: '남아프리카공화국', region: '유럽·아프리카', lat: -26.14, lon: 28.24 },
  // ---- 추가 공항 ----
  // 한국
  { code: 'MWX', en: 'Muan', city: '무안', country: '대한민국', region: '한국', lat: 34.99, lon: 126.38 },
  { code: 'KPO', en: 'Pohang', city: '포항경주', country: '대한민국', region: '한국', lat: 35.99, lon: 129.42 },
  { code: 'HIN', en: 'Sacheon', city: '사천', country: '대한민국', region: '한국', lat: 35.09, lon: 128.07 },
  { code: 'WJU', en: 'Wonju', city: '원주', country: '대한민국', region: '한국', lat: 37.44, lon: 127.96 },
  { code: 'KUV', en: 'Gunsan', city: '군산', country: '대한민국', region: '한국', lat: 35.90, lon: 126.62 },
  // 일본
  { code: 'NGO', en: 'Nagoya', city: '나고야', country: '일본', region: '일본', lat: 34.86, lon: 136.81 },
  { code: 'ITM', en: 'Osaka Itami', city: '오사카 이타미', country: '일본', region: '일본', lat: 34.79, lon: 135.44 },
  { code: 'KOJ', en: 'Kagoshima', city: '가고시마', country: '일본', region: '일본', lat: 31.80, lon: 130.72 },
  { code: 'HIJ', en: 'Hiroshima', city: '히로시마', country: '일본', region: '일본', lat: 34.44, lon: 132.92 },
  { code: 'SDJ', en: 'Sendai', city: '센다이', country: '일본', region: '일본', lat: 38.14, lon: 140.92 },
  { code: 'KMJ', en: 'Kumamoto', city: '구마모토', country: '일본', region: '일본', lat: 32.84, lon: 130.86 },
  { code: 'OIT', en: 'Oita', city: '오이타', country: '일본', region: '일본', lat: 33.48, lon: 131.74 },
  { code: 'NGS', en: 'Nagasaki', city: '나가사키', country: '일본', region: '일본', lat: 32.92, lon: 129.91 },
  { code: 'MYJ', en: 'Matsuyama', city: '마쓰야마', country: '일본', region: '일본', lat: 33.83, lon: 132.70 },
  { code: 'TAK', en: 'Takamatsu', city: '다카마쓰', country: '일본', region: '일본', lat: 34.21, lon: 134.02 },
  { code: 'OKJ', en: 'Okayama', city: '오카야마', country: '일본', region: '일본', lat: 34.76, lon: 133.86 },
  { code: 'KIJ', en: 'Niigata', city: '니가타', country: '일본', region: '일본', lat: 37.96, lon: 139.12 },
  { code: 'AOJ', en: 'Aomori', city: '아오모리', country: '일본', region: '일본', lat: 40.73, lon: 140.69 },
  { code: 'HKD', en: 'Hakodate', city: '하코다테', country: '일본', region: '일본', lat: 41.77, lon: 140.82 },
  { code: 'KMQ', en: 'Komatsu', city: '고마쓰', country: '일본', region: '일본', lat: 36.39, lon: 136.41 },
  { code: 'FSZ', en: 'Shizuoka', city: '시즈오카', country: '일본', region: '일본', lat: 34.80, lon: 138.19 },
  { code: 'KKJ', en: 'Kitakyushu', city: '기타큐슈', country: '일본', region: '일본', lat: 33.85, lon: 131.03 },
  { code: 'ISG', en: 'Ishigaki', city: '이시가키', country: '일본', region: '일본', lat: 24.40, lon: 124.25 },
  { code: 'MMY', en: 'Miyako', city: '미야코', country: '일본', region: '일본', lat: 24.78, lon: 125.30 },
  // 중화권
  { code: 'PKX', en: 'Beijing Daxing', city: '베이징 다싱', country: '중국', region: '중화권', lat: 39.51, lon: 116.41 },
  { code: 'SHA', en: 'Shanghai Hongqiao', city: '상하이 훙차오', country: '중국', region: '중화권', lat: 31.20, lon: 121.34 },
  { code: 'CAN', en: 'Guangzhou', city: '광저우', country: '중국', region: '중화권', lat: 23.39, lon: 113.30 },
  { code: 'SZX', en: 'Shenzhen', city: '선전', country: '중국', region: '중화권', lat: 22.64, lon: 113.81 },
  { code: 'CTU', en: 'Chengdu', city: '청두', country: '중국', region: '중화권', lat: 30.31, lon: 104.44 },
  { code: 'CKG', en: 'Chongqing', city: '충칭', country: '중국', region: '중화권', lat: 29.72, lon: 106.64 },
  { code: 'XIY', en: "Xi'an", city: '시안', country: '중국', region: '중화권', lat: 34.45, lon: 108.75 },
  { code: 'KMG', en: 'Kunming', city: '쿤밍', country: '중국', region: '중화권', lat: 25.10, lon: 102.93 },
  { code: 'HGH', en: 'Hangzhou', city: '항저우', country: '중국', region: '중화권', lat: 30.23, lon: 120.43 },
  { code: 'NKG', en: 'Nanjing', city: '난징', country: '중국', region: '중화권', lat: 31.74, lon: 118.86 },
  { code: 'TAO', en: 'Qingdao', city: '칭다오', country: '중국', region: '중화권', lat: 36.36, lon: 120.09 },
  { code: 'DLC', en: 'Dalian', city: '다롄', country: '중국', region: '중화권', lat: 38.97, lon: 121.54 },
  { code: 'SHE', en: 'Shenyang', city: '선양', country: '중국', region: '중화권', lat: 41.64, lon: 123.48 },
  { code: 'HRB', en: 'Harbin', city: '하얼빈', country: '중국', region: '중화권', lat: 45.62, lon: 126.25 },
  { code: 'YNJ', en: 'Yanji', city: '옌지', country: '중국', region: '중화권', lat: 42.88, lon: 129.45 },
  { code: 'TSN', en: 'Tianjin', city: '톈진', country: '중국', region: '중화권', lat: 39.12, lon: 117.35 },
  { code: 'CGO', en: 'Zhengzhou', city: '정저우', country: '중국', region: '중화권', lat: 34.52, lon: 113.84 },
  { code: 'WUH', en: 'Wuhan', city: '우한', country: '중국', region: '중화권', lat: 30.78, lon: 114.21 },
  { code: 'CSX', en: 'Changsha', city: '창사', country: '중국', region: '중화권', lat: 28.19, lon: 113.22 },
  { code: 'XMN', en: 'Xiamen', city: '샤먼', country: '중국', region: '중화권', lat: 24.54, lon: 118.13 },
  { code: 'SYX', en: 'Sanya', city: '싼야', country: '중국', region: '중화권', lat: 18.30, lon: 109.41 },
  { code: 'HAK', en: 'Haikou', city: '하이커우', country: '중국', region: '중화권', lat: 19.94, lon: 110.46 },
  { code: 'URC', en: 'Urumqi', city: '우루무치', country: '중국', region: '중화권', lat: 43.91, lon: 87.47 },
  { code: 'LXA', en: 'Lhasa', city: '라싸', country: '중국', region: '중화권', lat: 29.30, lon: 90.91 },
  { code: 'MFM', en: 'Macau', city: '마카오', country: '마카오', region: '중화권', lat: 22.15, lon: 113.59 },
  { code: 'TSA', en: 'Taipei Songshan', city: '타이베이 쑹산', country: '대만', region: '중화권', lat: 25.07, lon: 121.55 },
  { code: 'KHH', en: 'Kaohsiung', city: '가오슝', country: '대만', region: '중화권', lat: 22.58, lon: 120.35 },
  { code: 'RMQ', en: 'Taichung', city: '타이중', country: '대만', region: '중화권', lat: 24.26, lon: 120.62 },
  // 동남아시아
  { code: 'DMK', en: 'Bangkok Don Mueang', city: '방콕 돈므앙', country: '태국', region: '동남아시아', lat: 13.91, lon: 100.61 },
  { code: 'HKT', en: 'Phuket', city: '푸껫', country: '태국', region: '동남아시아', lat: 8.11, lon: 98.32 },
  { code: 'CNX', en: 'Chiang Mai', city: '치앙마이', country: '태국', region: '동남아시아', lat: 18.77, lon: 98.96 },
  { code: 'PQC', en: 'Phu Quoc', city: '푸꾸옥', country: '베트남', region: '동남아시아', lat: 10.17, lon: 103.99 },
  { code: 'CXR', en: 'Nha Trang', city: '나트랑', country: '베트남', region: '동남아시아', lat: 12.00, lon: 109.22 },
  { code: 'HPH', en: 'Hai Phong', city: '하이퐁', country: '베트남', region: '동남아시아', lat: 20.82, lon: 106.72 },
  { code: 'VTE', en: 'Vientiane', city: '비엔티안', country: '라오스', region: '동남아시아', lat: 17.99, lon: 102.56 },
  { code: 'PNH', en: 'Phnom Penh', city: '프놈펜', country: '캄보디아', region: '동남아시아', lat: 11.55, lon: 104.84 },
  { code: 'SAI', en: 'Siem Reap', city: '시엠레아프', country: '캄보디아', region: '동남아시아', lat: 13.37, lon: 104.22 },
  { code: 'RGN', en: 'Yangon', city: '양곤', country: '미얀마', region: '동남아시아', lat: 16.91, lon: 96.13 },
  { code: 'CRK', en: 'Clark', city: '클라크', country: '필리핀', region: '동남아시아', lat: 15.19, lon: 120.56 },
  { code: 'KLO', en: 'Kalibo', city: '칼리보(보라카이)', country: '필리핀', region: '동남아시아', lat: 11.68, lon: 122.38 },
  { code: 'BKI', en: 'Kota Kinabalu', city: '코타키나발루', country: '말레이시아', region: '동남아시아', lat: 5.94, lon: 116.05 },
  { code: 'PEN', en: 'Penang', city: '페낭', country: '말레이시아', region: '동남아시아', lat: 5.30, lon: 100.28 },
  { code: 'LGK', en: 'Langkawi', city: '랑카위', country: '말레이시아', region: '동남아시아', lat: 6.33, lon: 99.73 },
  { code: 'BWN', en: 'Bandar Seri Begawan', city: '반다르스리브가완', country: '브루나이', region: '동남아시아', lat: 4.94, lon: 114.93 },
  { code: 'CGK', en: 'Jakarta', city: '자카르타', country: '인도네시아', region: '동남아시아', lat: -6.13, lon: 106.66 },
  { code: 'SUB', en: 'Surabaya', city: '수라바야', country: '인도네시아', region: '동남아시아', lat: -7.38, lon: 112.79 },
  // 아시아 기타·중동
  { code: 'BOM', en: 'Mumbai', city: '뭄바이', country: '인도', region: '아시아·중동', lat: 19.09, lon: 72.87 },
  { code: 'BLR', en: 'Bengaluru', city: '벵갈루루', country: '인도', region: '아시아·중동', lat: 13.20, lon: 77.71 },
  { code: 'MAA', en: 'Chennai', city: '첸나이', country: '인도', region: '아시아·중동', lat: 12.99, lon: 80.17 },
  { code: 'CCU', en: 'Kolkata', city: '콜카타', country: '인도', region: '아시아·중동', lat: 22.65, lon: 88.45 },
  { code: 'KTM', en: 'Kathmandu', city: '카트만두', country: '네팔', region: '아시아·중동', lat: 27.70, lon: 85.36 },
  { code: 'DAC', en: 'Dhaka', city: '다카', country: '방글라데시', region: '아시아·중동', lat: 23.84, lon: 90.40 },
  { code: 'CMB', en: 'Colombo', city: '콜롬보', country: '스리랑카', region: '아시아·중동', lat: 7.18, lon: 79.88 },
  { code: 'MLE', en: 'Male', city: '말레', country: '몰디브', region: '아시아·중동', lat: 4.19, lon: 73.53 },
  { code: 'ISB', en: 'Islamabad', city: '이슬라마바드', country: '파키스탄', region: '아시아·중동', lat: 33.55, lon: 72.83 },
  { code: 'TAS', en: 'Tashkent', city: '타슈켄트', country: '우즈베키스탄', region: '아시아·중동', lat: 41.26, lon: 69.28 },
  { code: 'ALA', en: 'Almaty', city: '알마티', country: '카자흐스탄', region: '아시아·중동', lat: 43.35, lon: 77.04 },
  { code: 'NQZ', en: 'Astana', city: '아스타나', country: '카자흐스탄', region: '아시아·중동', lat: 51.02, lon: 71.47 },
  { code: 'KHV', en: 'Khabarovsk', city: '하바롭스크', country: '러시아', region: '아시아·중동', lat: 48.53, lon: 135.19 },
  { code: 'UUS', en: 'Yuzhno-Sakhalinsk', city: '유즈노사할린스크', country: '러시아', region: '아시아·중동', lat: 46.89, lon: 142.72 },
  { code: 'IKT', en: 'Irkutsk', city: '이르쿠츠크', country: '러시아', region: '아시아·중동', lat: 52.27, lon: 104.39 },
  { code: 'OVB', en: 'Novosibirsk', city: '노보시비르스크', country: '러시아', region: '아시아·중동', lat: 55.01, lon: 82.65 },
  { code: 'DOH', en: 'Doha', city: '도하', country: '카타르', region: '아시아·중동', lat: 25.27, lon: 51.61 },
  { code: 'AUH', en: 'Abu Dhabi', city: '아부다비', country: '아랍에미리트', region: '아시아·중동', lat: 24.43, lon: 54.65 },
  { code: 'RUH', en: 'Riyadh', city: '리야드', country: '사우디아라비아', region: '아시아·중동', lat: 24.96, lon: 46.70 },
  { code: 'JED', en: 'Jeddah', city: '제다', country: '사우디아라비아', region: '아시아·중동', lat: 21.68, lon: 39.16 },
  { code: 'MCT', en: 'Muscat', city: '무스카트', country: '오만', region: '아시아·중동', lat: 23.59, lon: 58.28 },
  { code: 'KWI', en: 'Kuwait', city: '쿠웨이트', country: '쿠웨이트', region: '아시아·중동', lat: 29.24, lon: 47.97 },
  { code: 'BAH', en: 'Bahrain', city: '바레인', country: '바레인', region: '아시아·중동', lat: 26.27, lon: 50.63 },
  { code: 'AMM', en: 'Amman', city: '암만', country: '요르단', region: '아시아·중동', lat: 31.72, lon: 35.99 },
  { code: 'TLV', en: 'Tel Aviv', city: '텔아비브', country: '이스라엘', region: '아시아·중동', lat: 32.01, lon: 34.89 },
  { code: 'SAW', en: 'Istanbul Sabiha Gokcen', city: '이스탄불 사비하괵첸', country: '튀르키예', region: '아시아·중동', lat: 40.90, lon: 29.31 },
  { code: 'AYT', en: 'Antalya', city: '안탈리아', country: '튀르키예', region: '아시아·중동', lat: 36.90, lon: 30.80 },
  // 오세아니아·태평양
  { code: 'MEL', en: 'Melbourne', city: '멜버른', country: '호주', region: '오세아니아·태평양', lat: -37.67, lon: 144.84 },
  { code: 'BNE', en: 'Brisbane', city: '브리즈번', country: '호주', region: '오세아니아·태평양', lat: -27.38, lon: 153.12 },
  { code: 'PER', en: 'Perth', city: '퍼스', country: '호주', region: '오세아니아·태평양', lat: -31.94, lon: 115.97 },
  { code: 'ADL', en: 'Adelaide', city: '애들레이드', country: '호주', region: '오세아니아·태평양', lat: -34.95, lon: 138.53 },
  { code: 'CNS', en: 'Cairns', city: '케언스', country: '호주', region: '오세아니아·태평양', lat: -16.88, lon: 145.75 },
  { code: 'OOL', en: 'Gold Coast', city: '골드코스트', country: '호주', region: '오세아니아·태평양', lat: -28.16, lon: 153.51 },
  { code: 'DRW', en: 'Darwin', city: '다윈', country: '호주', region: '오세아니아·태평양', lat: -12.41, lon: 130.88 },
  { code: 'CHC', en: 'Christchurch', city: '크라이스트처치', country: '뉴질랜드', region: '오세아니아·태평양', lat: -43.49, lon: 172.53 },
  { code: 'ZQN', en: 'Queenstown', city: '퀸스타운', country: '뉴질랜드', region: '오세아니아·태평양', lat: -45.02, lon: 168.74 },
  { code: 'WLG', en: 'Wellington', city: '웰링턴', country: '뉴질랜드', region: '오세아니아·태평양', lat: -41.33, lon: 174.81 },
  { code: 'NAN', en: 'Nadi', city: '난디', country: '피지', region: '오세아니아·태평양', lat: -17.76, lon: 177.44 },
  { code: 'SPN', en: 'Saipan', city: '사이판', country: '미국령 북마리아나', region: '오세아니아·태평양', lat: 15.12, lon: 145.73 },
  { code: 'ROR', en: 'Palau', city: '팔라우', country: '팔라우', region: '오세아니아·태평양', lat: 7.37, lon: 134.54 },
  { code: 'NOU', en: 'Noumea', city: '누메아', country: '뉴칼레도니아', region: '오세아니아·태평양', lat: -22.01, lon: 166.21 },
  { code: 'POM', en: 'Port Moresby', city: '포트모르즈비', country: '파푸아뉴기니', region: '오세아니아·태평양', lat: -9.44, lon: 147.22 },
  { code: 'PPT', en: 'Tahiti', city: '타히티', country: '프랑스령 폴리네시아', region: '오세아니아·태평양', lat: -17.55, lon: -149.61 },
  { code: 'OGG', en: 'Maui', city: '마우이', country: '미국', region: '오세아니아·태평양', lat: 20.90, lon: -156.43 },
  { code: 'KOA', en: 'Kona', city: '코나', country: '미국', region: '오세아니아·태평양', lat: 19.74, lon: -156.05 },
  // 아메리카
  { code: 'ANC', en: 'Anchorage', city: '앵커리지', country: '미국', region: '아메리카', lat: 61.17, lon: -149.99 },
  { code: 'PDX', en: 'Portland', city: '포틀랜드', country: '미국', region: '아메리카', lat: 45.59, lon: -122.60 },
  { code: 'SAN', en: 'San Diego', city: '샌디에이고', country: '미국', region: '아메리카', lat: 32.73, lon: -117.19 },
  { code: 'LAS', en: 'Las Vegas', city: '라스베이거스', country: '미국', region: '아메리카', lat: 36.08, lon: -115.15 },
  { code: 'PHX', en: 'Phoenix', city: '피닉스', country: '미국', region: '아메리카', lat: 33.43, lon: -112.01 },
  { code: 'SLC', en: 'Salt Lake City', city: '솔트레이크시티', country: '미국', region: '아메리카', lat: 40.79, lon: -111.98 },
  { code: 'DEN', en: 'Denver', city: '덴버', country: '미국', region: '아메리카', lat: 39.86, lon: -104.67 },
  { code: 'DFW', en: 'Dallas', city: '댈러스', country: '미국', region: '아메리카', lat: 32.90, lon: -97.04 },
  { code: 'IAH', en: 'Houston', city: '휴스턴', country: '미국', region: '아메리카', lat: 29.99, lon: -95.34 },
  { code: 'MSP', en: 'Minneapolis', city: '미니애폴리스', country: '미국', region: '아메리카', lat: 44.88, lon: -93.22 },
  { code: 'ORD', en: 'Chicago', city: '시카고', country: '미국', region: '아메리카', lat: 41.98, lon: -87.90 },
  { code: 'DTW', en: 'Detroit', city: '디트로이트', country: '미국', region: '아메리카', lat: 42.21, lon: -83.35 },
  { code: 'ATL', en: 'Atlanta', city: '애틀랜타', country: '미국', region: '아메리카', lat: 33.64, lon: -84.43 },
  { code: 'MCO', en: 'Orlando', city: '올랜도', country: '미국', region: '아메리카', lat: 28.43, lon: -81.31 },
  { code: 'MIA', en: 'Miami', city: '마이애미', country: '미국', region: '아메리카', lat: 25.80, lon: -80.29 },
  { code: 'IAD', en: 'Washington', city: '워싱턴 D.C.', country: '미국', region: '아메리카', lat: 38.95, lon: -77.46 },
  { code: 'PHL', en: 'Philadelphia', city: '필라델피아', country: '미국', region: '아메리카', lat: 39.87, lon: -75.24 },
  { code: 'EWR', en: 'Newark', city: '뉴어크', country: '미국', region: '아메리카', lat: 40.69, lon: -74.17 },
  { code: 'BOS', en: 'Boston', city: '보스턴', country: '미국', region: '아메리카', lat: 42.37, lon: -71.01 },
  { code: 'YYC', en: 'Calgary', city: '캘거리', country: '캐나다', region: '아메리카', lat: 51.13, lon: -114.01 },
  { code: 'YYZ', en: 'Toronto', city: '토론토', country: '캐나다', region: '아메리카', lat: 43.68, lon: -79.63 },
  { code: 'YUL', en: 'Montreal', city: '몬트리올', country: '캐나다', region: '아메리카', lat: 45.47, lon: -73.74 },
  { code: 'MEX', en: 'Mexico City', city: '멕시코시티', country: '멕시코', region: '아메리카', lat: 19.44, lon: -99.07 },
  { code: 'CUN', en: 'Cancun', city: '칸쿤', country: '멕시코', region: '아메리카', lat: 21.04, lon: -86.87 },
  { code: 'HAV', en: 'Havana', city: '아바나', country: '쿠바', region: '아메리카', lat: 22.99, lon: -82.41 },
  { code: 'SJU', en: 'San Juan', city: '산후안', country: '푸에르토리코', region: '아메리카', lat: 18.44, lon: -66.00 },
  { code: 'PTY', en: 'Panama City', city: '파나마시티', country: '파나마', region: '아메리카', lat: 9.07, lon: -79.38 },
  { code: 'BOG', en: 'Bogota', city: '보고타', country: '콜롬비아', region: '아메리카', lat: 4.70, lon: -74.15 },
  { code: 'UIO', en: 'Quito', city: '키토', country: '에콰도르', region: '아메리카', lat: -0.13, lon: -78.36 },
  { code: 'LIM', en: 'Lima', city: '리마', country: '페루', region: '아메리카', lat: -12.02, lon: -77.11 },
  { code: 'SCL', en: 'Santiago', city: '산티아고', country: '칠레', region: '아메리카', lat: -33.39, lon: -70.79 },
  { code: 'EZE', en: 'Buenos Aires', city: '부에노스아이레스', country: '아르헨티나', region: '아메리카', lat: -34.82, lon: -58.54 },
  { code: 'GIG', en: 'Rio de Janeiro', city: '리우데자네이루', country: '브라질', region: '아메리카', lat: -22.81, lon: -43.25 },
  // 유럽
  { code: 'KEF', en: 'Reykjavik', city: '레이캬비크', country: '아이슬란드', region: '유럽·아프리카', lat: 63.99, lon: -22.61 },
  { code: 'DUB', en: 'Dublin', city: '더블린', country: '아일랜드', region: '유럽·아프리카', lat: 53.42, lon: -6.27 },
  { code: 'EDI', en: 'Edinburgh', city: '에든버러', country: '영국', region: '유럽·아프리카', lat: 55.95, lon: -3.37 },
  { code: 'MAN', en: 'Manchester', city: '맨체스터', country: '영국', region: '유럽·아프리카', lat: 53.35, lon: -2.28 },
  { code: 'LIS', en: 'Lisbon', city: '리스본', country: '포르투갈', region: '유럽·아프리카', lat: 38.77, lon: -9.13 },
  { code: 'MAD', en: 'Madrid', city: '마드리드', country: '스페인', region: '유럽·아프리카', lat: 40.49, lon: -3.57 },
  { code: 'AGP', en: 'Malaga', city: '말라가', country: '스페인', region: '유럽·아프리카', lat: 36.67, lon: -4.50 },
  { code: 'PMI', en: 'Palma de Mallorca', city: '팔마 데 마요르카', country: '스페인', region: '유럽·아프리카', lat: 39.55, lon: 2.74 },
  { code: 'NCE', en: 'Nice', city: '니스', country: '프랑스', region: '유럽·아프리카', lat: 43.66, lon: 7.21 },
  { code: 'BRU', en: 'Brussels', city: '브뤼셀', country: '벨기에', region: '유럽·아프리카', lat: 50.90, lon: 4.48 },
  { code: 'GVA', en: 'Geneva', city: '제네바', country: '스위스', region: '유럽·아프리카', lat: 46.24, lon: 6.11 },
  { code: 'DUS', en: 'Dusseldorf', city: '뒤셀도르프', country: '독일', region: '유럽·아프리카', lat: 51.29, lon: 6.77 },
  { code: 'HAM', en: 'Hamburg', city: '함부르크', country: '독일', region: '유럽·아프리카', lat: 53.63, lon: 9.99 },
  { code: 'MUC', en: 'Munich', city: '뮌헨', country: '독일', region: '유럽·아프리카', lat: 48.35, lon: 11.79 },
  { code: 'BER', en: 'Berlin', city: '베를린', country: '독일', region: '유럽·아프리카', lat: 52.37, lon: 13.50 },
  { code: 'CPH', en: 'Copenhagen', city: '코펜하겐', country: '덴마크', region: '유럽·아프리카', lat: 55.62, lon: 12.66 },
  { code: 'OSL', en: 'Oslo', city: '오슬로', country: '노르웨이', region: '유럽·아프리카', lat: 60.19, lon: 11.10 },
  { code: 'ARN', en: 'Stockholm', city: '스톡홀름', country: '스웨덴', region: '유럽·아프리카', lat: 59.65, lon: 17.92 },
  { code: 'TLL', en: 'Tallinn', city: '탈린', country: '에스토니아', region: '유럽·아프리카', lat: 59.41, lon: 24.83 },
  { code: 'RIX', en: 'Riga', city: '리가', country: '라트비아', region: '유럽·아프리카', lat: 56.92, lon: 23.97 },
  { code: 'VNO', en: 'Vilnius', city: '빌뉴스', country: '리투아니아', region: '유럽·아프리카', lat: 54.63, lon: 25.29 },
  { code: 'WAW', en: 'Warsaw', city: '바르샤바', country: '폴란드', region: '유럽·아프리카', lat: 52.17, lon: 20.97 },
  { code: 'VIE', en: 'Vienna', city: '빈', country: '오스트리아', region: '유럽·아프리카', lat: 48.11, lon: 16.57 },
  { code: 'BUD', en: 'Budapest', city: '부다페스트', country: '헝가리', region: '유럽·아프리카', lat: 47.44, lon: 19.26 },
  { code: 'ZAG', en: 'Zagreb', city: '자그레브', country: '크로아티아', region: '유럽·아프리카', lat: 45.74, lon: 16.07 },
  { code: 'DBV', en: 'Dubrovnik', city: '두브로브니크', country: '크로아티아', region: '유럽·아프리카', lat: 42.56, lon: 18.27 },
  { code: 'OTP', en: 'Bucharest', city: '부쿠레슈티', country: '루마니아', region: '유럽·아프리카', lat: 44.57, lon: 26.10 },
  { code: 'MXP', en: 'Milan', city: '밀라노', country: '이탈리아', region: '유럽·아프리카', lat: 45.63, lon: 8.72 },
  { code: 'VCE', en: 'Venice', city: '베네치아', country: '이탈리아', region: '유럽·아프리카', lat: 45.51, lon: 12.35 },
  { code: 'NAP', en: 'Naples', city: '나폴리', country: '이탈리아', region: '유럽·아프리카', lat: 40.88, lon: 14.29 },
  { code: 'MLA', en: 'Malta', city: '몰타', country: '몰타', region: '유럽·아프리카', lat: 35.86, lon: 14.48 },
  { code: 'ATH', en: 'Athens', city: '아테네', country: '그리스', region: '유럽·아프리카', lat: 37.94, lon: 23.94 },
  // 아프리카
  { code: 'CMN', en: 'Casablanca', city: '카사블랑카', country: '모로코', region: '유럽·아프리카', lat: 33.37, lon: -7.59 },
  { code: 'RAK', en: 'Marrakesh', city: '마라케시', country: '모로코', region: '유럽·아프리카', lat: 31.61, lon: -8.04 },
  { code: 'TUN', en: 'Tunis', city: '튀니스', country: '튀니지', region: '유럽·아프리카', lat: 36.85, lon: 10.23 },
  { code: 'HRG', en: 'Hurghada', city: '후르가다', country: '이집트', region: '유럽·아프리카', lat: 27.18, lon: 33.80 },
  { code: 'ADD', en: 'Addis Ababa', city: '아디스아바바', country: '에티오피아', region: '유럽·아프리카', lat: 8.98, lon: 38.80 },
  { code: 'NBO', en: 'Nairobi', city: '나이로비', country: '케냐', region: '유럽·아프리카', lat: -1.32, lon: 36.93 },
  { code: 'DAR', en: 'Dar es Salaam', city: '다르에스살람', country: '탄자니아', region: '유럽·아프리카', lat: -6.88, lon: 39.20 },
  { code: 'ZNZ', en: 'Zanzibar', city: '잔지바르', country: '탄자니아', region: '유럽·아프리카', lat: -6.22, lon: 39.22 },
  { code: 'LOS', en: 'Lagos', city: '라고스', country: '나이지리아', region: '유럽·아프리카', lat: 6.58, lon: 3.32 },
  { code: 'ACC', en: 'Accra', city: '아크라', country: '가나', region: '유럽·아프리카', lat: 5.61, lon: -0.17 },
  { code: 'CPT', en: 'Cape Town', city: '케이프타운', country: '남아프리카공화국', region: '유럽·아프리카', lat: -33.96, lon: 18.60 },
  { code: 'MRU', en: 'Mauritius', city: '모리셔스', country: '모리셔스', region: '유럽·아프리카', lat: -20.43, lon: 57.68 },
  { code: 'SEZ', en: 'Seychelles', city: '세이셸', country: '세이셸', region: '유럽·아프리카', lat: -4.67, lon: 55.52 },
];
